### ISSUE TITLE
file upload is slow

### ISSUE THREAD

**Issue by DaemonHc** [pistacheio/pistache#105]
We i want to store file from browser client, i use this method, but i find it is too slow, how to slove that.
this is my solution:
first get body, then store it to a file
 std::string body = req.body();
writeToFile("file", body);

void writeToFile(const string & filename, const string & data) {
        ofstream out;
        out.open(filename.c_str());
        out << data ;
        out.close();

    }

**Comment by xoac** [comment]
What do u mean by to slow? How slow?
How do u upload this file?
Can u give a full example how to reproduce this `slow` request?

_On code that u give I don't see anything that can go slow._

**Comment by DoraDreams** [comment]
Sorry!! 
I upload a video(mp4) which size is about 3mb,  then it takes me about 23 seconds to upload it. I do this operation from my local computer to virtual machine, so network is ok.

**Comment by xoac** [comment]
Can u give a full example? I want to test it.

**Comment by DoraDreams** [comment]
Sure, but the code is in my company computer, I can not get it until next monday. But the process is very simple. I will illustrate the process.
First, I post a video using http post method, which means that i put video data in http body.
Then, on server side, I use request to get http body, which returns a string to me.
Finally i write that data to file.
Next monday, i will paste my server code to let you test it. 
Can you give your contact to me .
Thank you.

**Comment by DoraDreams** [comment]
class MyHandler : public Http::Handler {

    HTTP_PROTOTYPE(MyHandler)

    void onRequest(
            const Http::Request& req,
            Http::ResponseWriter response) {

        if (req.resource() == "/handler") {
            if (req.method() == Http::Method::Post) {
                
                using namespace Http;

                auto query = req.query();
               
                if (query.has("cmd")) {
                    std::string params = query.getParameter("cmd");
                    
                   // auto test = chunked.get("chunked");
                    std::cout << "Using cmd parameter " << params << endl;

                    std::string body = req.body();
                    // std::cout << "test message: body is " << body << endl;
                    parseString(params);
                    writeToFile("test", body);

                    response.send(Http::Code::Ok, "ok");

                }
                else {
                    response.send(Http::Code::Ok, "No parameters");
                }

            }
        }
}

    void writeToFile(const string & filename, const string & data) {
        ofstream out;
        out.open(filename.c_str());
        out << data ;
        out.close();

    }

This is what i write

**Comment by xoac** [comment]
I will test it. But I can't do it today.

**Comment by xoac** [comment]
Ok. First of all you have compiled with some patch. In my version it's impossible to sending such big data.

# My used example:
```
#include <pistache/http.h>
#include <pistache/endpoint.h>
#include <fstream>
#include <chrono>
#include <iostream>

using namespace Pistache;
using namespace std;

void writeToFile(const string & filename, const string & data) {
    ofstream out;
    out.open(filename.c_str());
    out << data ;
    out.close();
}

class MyHandler : public Http::Handler {
    HTTP_PROTOTYPE(MyHandler);

    void onRequest( const Http::Request& req, Http::ResponseWriter response) {
        if (req.resource() == "/handler") {

            if (req.method() == Http::Method::Post)
            {
                using namespace Http;

                auto s = std::chrono::steady_clock::now();
                writeToFile("test", req.body());
                auto dt = std::chrono::steady_clock::now() - s;
                cout << "Czas zapisu: " << std::chrono::duration_cast<std::chrono::microseconds>(dt).count()<< endl;
                response.send(Http::Code::Ok);
            }
        }
    }
}

int main(int argc, char **argv)
{
        Http::listenAndServe<MyHandler>("*:9080");
}
```
And python testing function:

**Comment by DoraDreams** [comment]
Sorry，  I forget one thing。
In order to post such big file, i change **common.h(include/pistache/common.h)** file. 
    static constexpr int MaxBuffer = 1024 * 1024 * 7; 
    static constexpr int ChunkSize = 1024 * 1024;

**Comment by xoac** [comment]
So your issue is connected with #75 #87 #83. In my opinion this should be first resolved to look at performance. For now I don't need such big file to transfer.  But you can cooperate with @kennymalac ( #75 ).

**Comment by DoraDreams** [comment]
Thank you for your answer.

**Comment by AdrianCX** [comment]
As a note, I don't really see the slowdown on latest master:

You only need to do:
static constexpr size_t DefaultMaxPayload = 1024*1024*10;

You don't need to change "MaxBuffer", that is counterproductive.

Running a python script that posts a random binary file to echo endpoint and then writes it back to disk as it receives it takes ~0.2 seconds.

That can be further improved by using memory pools as perf shows it stays quite a bit in allocators.


```
~/pistache/examples$ python3 test.py 
<Response [200]>
0.14371061325073242

~/pistache/examples$ sha1sum s.jpg out.jpg 
f0a40e80bfc8a98f5f8f78e2f532bfd2b7d3d937  s.jpg
f0a40e80bfc8a98f5f8f78e2f532bfd2b7d3d937  out.jpg

~/pistache/examples$ cat test.py 

import requests
import time

if __name__ == '__main__':
    start_time = time.time()
    url = 'http://localhost:9080/echo'
    j = open("s.jpg", "rb")
    r = requests.post(url, data=j.read())
    print(r)
    with open("out.jpg", 'wb') as fd:
        for chunk in r.iter_content(chunk_size=128):
            fd.write(chunk)
    elapsed_time = time.time() - start_time
    print(elapsed_time)
```

Quick perf report:
```
  20,05%  run_http_server  run_http_server      [.] _ZNSt6vectorIcSaIcEE9push_backERKc
  17,58%  run_http_server  run_http_server      [.] _ZNSt11__copy_moveILb0ELb0ESt26random_access_iterator_tagE8__copy_mIPKcSt20back_insert_iteratorISt6vectorIcSaIcEEEEET0_T_SB_SA_
  14,62%  run_http_server  run_http_server      [.] _ZN9__gnu_cxx13new_allocatorIcE9constructIcJRKcEEEvPT_DpOT0_
   7,21%  run_http_server  run_http_server      [.] _ZNSt20back_insert_iteratorISt6vectorIcSaIcEEEaSERKc
   6,47%  run_http_server  run_http_server      [.] _ZNSt16allocator_traitsISaIcEE9constructIcJRKcEEEvRS0_PT_DpOT0_
```

**Comment by mochechan** [comment]
> Ok. First of all you have compiled with some patch. In my version it's impossible to sending such big data.
> # My ready to copy example:
> 
> ```
> #include <pistache/http.h>
> #include <pistache/endpoint.h>
> #include <fstream>
> #include <chrono>
> #include <iostream>
> 
> using namespace Pistache;
> using namespace std;
> 
> void writeToFile(const string & filename, const string & data) {
>     ofstream out;
>     out.open(filename.c_str());
>     out << data ;
>     out.close();
> }
> 
> class MyHandler : public Http::Handler {
>     HTTP_PROTOTYPE(MyHandler);
> 
>     void onRequest( const Http::Request& req, Http::ResponseWriter response) {
>         if (req.resource() == "/handler") {
> 
>             if (req.method() == Http::Method::Post)
>             {
>                 using namespace Http;
> 
>                 auto s = std::chrono::steady_clock::now();
>                 writeToFile("test", req.body());
>                 auto dt = std::chrono::steady_clock::now() - s;
>                 cout << "Czas zapisu: " << std::chrono::duration_cast<std::chrono::microseconds>(dt).count()<< endl;
>                 response.send(Http::Code::Ok);
>             }
>         }
>     }
> }
> 
> int main(int argc, char **argv)
> {
>         Http::listenAndServe<MyHandler>("*:9080");
> }
> ```
> 
> # And python testing function:
> 
> http://docs.python-requests.org/en/master/user/install/#install
> 
> ```
> import requests
> import time
> 
> if __name__ == '__main__':
>     start_time = time.time()
>     url = 'http://localhost:9080/handler'
>     j = open("s.jpg", "rb")
>     r = requests.post(url, data=j.read())
>     print(r.text)
>     elapsed_time = time.time() - start_time
>     print(elapsed_time)
> ```
> 
> You need to provide my information about patch u have included during compilation.

The code makes the following compile error:
error: could not convert ‘(const char*)"*:9080"’ from ‘const char*’ to ‘Pistache::Address’
   39 | int main(int argc, char** argv) { Http::listenAndServe<MyHandler>("*:9080"); }
      |                                                                   ^~~~~~~~
      |                                                                   |
      |                                                                   const char*
