### ISSUE TITLE
Problems when installing pistache

### ISSUE THREAD

**Issue by zhangsh0327** [pistacheio/pistache#1068]
When i install pistache by using cmake, I found that  after I execute the "make install" command, it will occur an error. 
No rule to make target ”install'.  Stop.

Does anyone have this problem?

**Comment by Tachi107** [comment]
Hi, as mentioned in the [readme](https://github.com/pistacheio/pistache#building-from-source) and in the (now inaccessible) pistache.io website, Pistache is installable using the Meson build system. The install target was removed from CMake some time ago, to reduce maintenance of two different build systems. You can easily obtain Meson from your system's package manager (`apt install meson`), or pip (`pip install --user meson`)

**Comment by zhangsh0327** [comment]
Thank you. But when I install it by using meson, I met another problem. 
undefined reference to `std::filesystem::path::_M_split_cmpts()'
undefined reference to `std::filesystem::canonical(std::filesystem::path const&)'
My system is Centos7, and gcc8. 
Could you have any idea？

**Comment by Tachi107** [comment]
That's a bug / limitation in old GCC / libstdc++ versions. Even if you compile in C++17 mode, GCC versions older than 9.1 require you to pass the `-lstdc++fs` flag to use `std::filesystem` functions :/

Further info [here](https://en.cppreference.com/w/cpp/filesystem#Notes).

**Comment by zhangsh0327** [comment]
Thank you very much for your prompt reply. But after I skip the swagger portion, it still occurs an error. Like this,

> src/libpistache.so.0.0.3.p/server_router.cc.o: In function Pistache::Rest::Router::initFromDescription(Pistache::Rest::Description const&)':
> router.cc:(.text+0x423f): undefined reference to 'Pistache::Rest::Schema::PathGroup::flatBegin() const'
> router.cc:(.text+0x424a): undefined reference to 'Pistache::Rest::Schema::PathGroup::flatEnd() const'

Do you know why?

**Comment by Tachi107** [comment]
Hey @zhangsh0327 could you check if the latest commit solves your issue?

**Comment by zhangsh0327** [comment]
Sorry for the late reply. Yes, I can install it. Thank you very much.
