### ISSUE TITLE
Inconsistent renaming library to pistache

### ISSUE THREAD

**Issue by maximilianemanuel** [pistacheio/pistache#109]
in commit 6278d88f458d0b3db89b1521dc456c7d03d11179 the library has been renamed from "Net" to "Pistache", but the example file which is cited in the README file has not been adapted so far:
pistache/examples/hello_server.cc:
`using namespace Pistache;`
pistache/README.md

**Comment by xoac** [comment]
All documentation still use "Net" http://pistache.io/guide/.
There will be nice if there will be information about that change. But it looks like @ oktal don't have time lastly.

**Comment by oktal** [comment]
Hello,

You're right. I still have some cleanup to do about that. Will do this week-end

**Comment by xinthose** [comment]
bump

**Comment by sandakith** [comment]
This is a common problem in examples too. I created a pull request ca316d3 to update the example.
