### ISSUE TITLE
how can I get 0.0.2 version?

### ISSUE THREAD

**Issue by DipsyZ** [pistacheio/pistache#1099]
I download a open source code which is using the 0.0.2version like this:
![image](https://user-images.githubusercontent.com/31218180/194262279-4eaa6fb4-cdcc-452b-921c-a0c1f4d82881.png)
I download pistache master-branch source code and build it which is 0.0.5 I think
when I make the open source code there are a lot of error 
<img width="997" alt="image" src="https://user-images.githubusercontent.com/31218180/194262770-e823eed9-1156-4853-a7b5-e2d8be85fd64.png">
I am wondering if it is the version difference cause the problem

**Comment by DipsyZ** [comment]
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/31218180/194274573-399824c0-6410-4b4e-ba7d-e8061f31070a.png">

**Comment by Tachi107** [comment]
Hi, what project using Pistache did you download? Also, what version of C++ are you using? Pistache requires C++17

**Comment by DipsyZ** [comment]
thank u sooo much for reply, I change to use C++17 and the errors in the first pics have solved.
but there still remain error 
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/31218180/194465853-df435a1e-09ba-4a8d-bc49-f3a630e528fe.png">
is it caused by Pistachio package?I'm not sure

(the open source project is [here](https://github.com/tmkasun/streaming_graph_partitioning))

**Comment by DipsyZ** [comment]
> thank u sooo much for reply, I change to use C++17 and the errors in the first pics have solved. but there still remain error <img alt="image" width="1229" src="https://user-images.githubusercontent.com/31218180/194465853-df435a1e-09ba-4a8d-bc49-f3a630e528fe.png"> is it caused by Pistachio package?I'm not sure
> 
> (the open source project is [here](https://github.com/tmkasun/streaming_graph_partitioning))

I have solved this error, thank you so much

**Comment by Tachi107** [comment]
Nice to hear!
