### ISSUE TITLE
Support for Ubuntu 22.10

### ISSUE THREAD

**Issue by philippsaul** [pistacheio/pistache#1106]
Hey there! 
I like your project and want to know when you will add support for ubuntu 22.10. I can't find it in the unstable ppa.

**Comment by kiplingw** [comment]
Thanks @philippsaul. I've just added Kinetic and Lunar to the list of releases in the PPA build recipe. Notwithstanding any potential build errors, you should see packages for both in the next hour or so.

**Comment by philippsaul** [comment]
Thanks @kiplingw! I can see the packages and now it's working.

**Comment by philippsaul** [comment]
Hey @kiplingw , could you please add a distribution template for Raspbian/bullseye? I would like to use pistache on my raspberry pi 4.
