### ISSUE TITLE
Windows Builds

### ISSUE THREAD

**Issue by Rxann** [pistacheio/pistache#1128]
Could builds for windows be released?

**Comment by kiplingw** [comment]
Thanks @Rxann, but this has been asked many times already. We don't have any plans on porting the library to legacy systems.

**Comment by Rxann** [comment]
Thanks

**Comment by Tachi107** [comment]
Hi @Rxann, yeah as Kip said Windows is not currently a focus for the project. You can find more detailed info in issue #6, it's not trivial to port Pistache to non-Linux OSes
