### ISSUE TITLE
build error with latest master

### ISSUE THREAD

**Issue by lbxx11** [pistacheio/pistache#1132]
![截屏2023-05-28 23 36 50](https://github.com/pistacheio/pistache/assets/116659514/e944ec46-d7e9-47e4-8b78-418bc009bc4a)
Hi , I'm building with latest master, use:
```meson setup build \
    --buildtype=release \
    -DPISTACHE_USE_SSL=true \
    -DPISTACHE_BUILD_EXAMPLES=true \
    -DPISTACHE_BUILD_TESTS=true \
    -DPISTACHE_BUILD_DOCS=false \
    --prefix="$PWD/prefix"
```
but it shows error showed in the pic above, and I do have libcurl install(showed in the pic above)

**platform**:
```
NAME="AlmaLinux"
VERSION="9.2 (Turquoise Kodkod)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.2 (Turquoise Kodkod)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"
ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

**Comment by Tachi107** [comment]
Hi @lbxx11, that looks like the libcurl runtime library, not the development one. The libcurl you need should be in a package named `libcurl-devel` on RHEL and derivatives.

By the way, libcurl is only needed if you want to run the tests, it isn't otherwise

**Comment by lbxx11** [comment]
Thanks a lot!
