### ISSUE TITLE
Want to contribute by building the documentation site for pistache

### ISSUE THREAD

**Issue by ansh-devs** [pistacheio/pistache#1160]
I am an enthusiastic developer with a deep passion for **Pistache**. Having extensively used the framework for various projects, I am genuinely impressed with its capabilities and potential to revolutionize the development landscape. However, while exploring the framework's features, I noticed that there is a significant need for a comprehensive and **user-friendly documentation site**.

The existing documentation, though valuable, lacks the cohesion and structure necessary to guide developers of all skill levels effectively. As a result, newcomers often face challenges when trying to understand and harness the full potential of the framework. As a dedicated supporter of the project, I would like to propose a collaboration to build a top-notch documentation site for **Pistache**.
reach out to me via mail : me@anshdevs.in

Regards,
Ansh Garhewal

**Comment by Tachi107** [comment]
Hi @ansh-devs, thanks for the issue. Patches welcome!

Would it be ok to move the discussion in issue #875? There's some information about our current documentation setup (we use Docusaurus, located in the `pistache.io` folder). If it is, please close this issue so that we can continue there.

**Comment by ansh-devs** [comment]
Yeah, Sure
