### ISSUE TITLE
[BUG] Fails to fetch build dependencies in autopkgtest

### ISSUE THREAD

**Issue by kiplingw** [pistacheio/pistache#1171]
When attempting to test Pistache CI in autopkgtest(1) it fails before it can build with:

```
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 13) meson (>= 0.50.0) libcurl4-openssl-dev libgmock-dev (>= 1.11.0) | googletest (>= 1.11.0) libssl-dev pkg-config rapidjson-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

After several hours of trying to debug autopkgtest(1), shelling into the test bed, and verifying that the complained about dependencies are available from the package manager (and installable), I am still at a loss for why this is happening. All of the above dependencies appear to be correctly defined in `debian/control`.

@Tachi107 are you able to replicate at your end?

**Comment by Tachi107** [comment]
Hi Kip, the build failed once because of a missing dependency on `zlib1g-dev | libz-dev`, but you added the former since then. Are you still facing issues? I saw that it's still failing on armhf, but that's not directly related to zlib.

**Comment by kiplingw** [comment]
Hey @Tachi107. Yes, it is [still failing](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+build/27026319) to build due to the missing `zlib.h` header. It looks like the builder for some reason tried to build using the revision previous to my fix. Did I not push my changes to the correct branch perhaps?

**Comment by Tachi107** [comment]
> Yes, it is [still failing](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+build/27026319) to build due to the missing `zlib.h` header

That's a log of an older build which didn't include your fix; if you take a look at the following log, you can see that the build succeeds (click on the singular binary builds): <https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+recipebuild/3640662>

**Comment by kiplingw** [comment]
I fixed the zlib issue, but for me its still failing in autopkgtest for the initial reason that _none_ of the build dependencies are being pulled.

**Comment by Tachi107** [comment]
Il giorno mar 28 nov 2023 alle 15:00:34 -08:00:00, Kip 
***@***.***> ha scritto:
> I fixed the zlib issue, but for me its still failing in autopkgtest 
> for the initial reason that none of the build dependencies are being 
> pulled.
> 

I don't see how this is an issue in pistache, tough... Since the PPA 
builds fine, and we didn't change anything particular, maybe it's an 
issue in your environment? Did you try to build by using autopkgtest in 
e.g. a clean VM?

I didn't myself, but I'll try to tomorrow.

**Comment by kiplingw** [comment]
Well if it's a problem with any of the test harnesses specified in `debian/tests/control`, then it's a Pistache problem. But you're right, it could be something wrong with my environment. I'll keep investigating.

**Comment by kiplingw** [comment]
I still can't figure it out, but I suspect now that this is a problem with my autopkgtest setup and anything in Pistache.
