### ISSUE TITLE
Endpoint::Options::backlog_ is not used

### ISSUE THREAD

**Issue by jiankyu** [pistacheio/pistache#1194]
The Endpoint::Options struct has a member called "backlog_", this member is not passed down to listener::init(). As a result, the default argument in the method declaration is used, which is always 128.

**Comment by kiplingw** [comment]
Thanks @jiankyu. If you'd like to submit a PR we'll have a look.

**Comment by jiankyu** [comment]
Yes, will submit a PR to fix this. Thanks!
