### ISSUE TITLE
add support for `meson wrap`

### ISSUE THREAD

**Issue by Crazyokd** [pistacheio/pistache#1227]
pistache is always used as a library and also supports meson, so is it possible to consider supporting `meson wrap`?

**Comment by kiplingw** [comment]
Is there an advantage to meson wrap over the ubiquitous `pkg-config`?

**Comment by Crazyokd** [comment]
from my view, meson become more and more popular.
And Pistache itself also support meson build and uses several subprojects.

And if it support [meson subprojects](https://mesonbuild.com/Subprojects.html)
I just need reference `pistache_dep` in my meson project.

**Comment by Tachi107** [comment]
Hi @Crazyokd, Pistache can be trivially added as a wrap since it already uses Meson. You just need to submit a patch to <https://github.com/mesonbuild/wrapdb>
