### ISSUE TITLE
Pistache when compiled with SSL gives SIGABRT when, its .so files are called to init a server.

### ISSUE THREAD

**Issue by thatsmeray98** [pistacheio/pistache#1234]
I have following requirements, I have been using Pistache for http but, now I want to have https (i.e. SSL connection) with it. I tried with already present .so files but, it gives some-error as "PISTACHE WAS COMPILED FOR SSL" so I tried following steps to get Pistache compiled for SSL but, it giving SIGABRT when, I'm trying to use newly generated ".so" files generated from pistache master branch code.

I had followed following steps to generate "libpistache.so" files: 
```
git clone "https://github.com/pistacheio/pistache.git"
cd pistache
mkdir build
cd build
cmake3 -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DPISTACHE_USE_SSL=ON ..
make

```
Above steps generates "libpistache.so" files at "./build/src/" directory. Now I used these lines of code to init a server for both SSL and non-SSL connection. Here's the code for it:

```
        Pistache::Address addr(Pistache::Ipv4::any(), Pistache::Port(mListeningPort));
        // Case - 1
        //std::shared_ptr<Http::Endpoint> mHttpEndpoint = std::make_shared<Http::Endpoint>(addr);
        // Case - 2
        boost::shared_ptr<Http::Endpoint> mHttpEndpoint = boost::make_shared<Http::Endpoint>(addr);
        auto opts = Http::Endpoint::options().threads(mNumThreads).maxRequestSize(mMaxRequestSize).flags(Tcp::Options::ReuseAddr).bodyTimeout(std::chrono::seconds(mReqBodyTimeoutSec));
        if (mHttps == true)
                  mHttpEndpoint->useSSL("./certificates/mydomain.com.crt","./certificates/mydomain.com.key",false,nullptr);
        mHttpEndpoint->init(opts);
```

In both these cases the mHttpEndPoint->init(opts) is the point where the STGABRT occurs with following error displayed on console : "malloc.c:2415: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed."

Here's the backtrace for the error -> 
(gdb) bt
#0  0x00007ffff5a565ef in raise () from /lib64/libc.so.6
#1  0x00007ffff5a29e65 in abort () from /lib64/libc.so.6
#2  0x00007ffff5a9ecba in __malloc_assert () from /lib64/libc.so.6
#3  0x00007ffff5aa1528 in sysmalloc () from /lib64/libc.so.6
#4  0x00007ffff5aa2360 in _int_malloc () from /lib64/libc.so.6
#5  0x00007ffff5aa3492 in malloc () from /lib64/libc.so.6
#6  0x00007ffff640fd7c in operator new(unsigned long) () from /lib64/libstdc++.so.6
#7  0x00007ffff7f621f3 in Pistache::Http::Endpoint::init(Pistache::Http::Endpoint::Options const&) () from /etc/ross_controller-1/lib/libpistache.so.0
#8  0x0000000000677c4a in TestApp::Init (this=0x8d9580) at PistacheTestApp/TestApp.cpp:7

What might be causing the issue and how can I resolve it..??

**Comment by kiplingw** [comment]
Hey @thatsmeray98. Can you try building your application against the precompiled [packages](https://github.com/pistacheio/pistache?tab=readme-ov-file#ubuntu-ppa-unstable) in the PPA? Normal users shouldn't need to build from source in most situations unless they're testing changes to it.

My guess is there's an ABI mismatch in how you're building and linking against the library and that's causing the SIGABRT at runtime.

**Comment by thatsmeray98** [comment]
Thanks @kiplingw … ur guess was right.. as there was an ABI mismatch while building the pistache’s source code and my codebase integrated with pistache..!! It’s now working fine..!!

**Comment by kiplingw** [comment]
No worries @thatsmeray98. We're working on a way of preventing this from happening again in #1146.
