### ISSUE TITLE
Clang++ 19 compilation error: "no member named 'chain_'"

### ISSUE THREAD

**Issue by sjoubert** [pistacheio/pistache#1243]
Hi,

I'm currently hitting the following compilation error using the upcoming clang 19 release (using version `1:19.1.0~++rc4-5` from Debian testing):
```
In file included from <project>/pistache_output/api/MyProjectAPIInterface.h:22:
In file included from <project>/pistache_output/api/ApiBase.h:21:
In file included from /usr/include/pistache/router.h:23:
In file included from /usr/include/pistache/http.h:32:
/usr/include/pistache/async.h:711:45: error: no member named 'chain_' in 'Chainer<void, type-parameter-1-0>'
  711 |                         auto core   = this->chain_;
      |                                       ~~~~  ^
```

Looking at the code `chain_`, indeed, does not exists. I'm not sure why this is an error now on clang (my guess is that it's try to constexpr run that code now). I'm assuming this code somehow is not used otherwise the error would triggered before.

If needed I can provide a patch/fix with some guidance to confirm to me which part is indeed not used/wrong:
* The `chain_` and `core->state` calls are wrong. Can they simply be removed or do they need to occur on the `chainCore` member
* Can the whole `Chainer<void, Dummy>` class specialization be removed?

**Comment by dgreatwood** [comment]
Hi Sylvain,

Thanks for raising this.

Looking at the code, I'm not 100% sure without further analysis but I think we might be able to simply change async.h:711 to:
`                        auto core   = chainCore;`

Could you try that in your environment?

And you're welcome to submit a PR if you have something you're comfortable with, and/or to discuss this with us further.

Thanks again!
