### ISSUE TITLE
Example Rest Post Body

### ISSUE THREAD

**Issue by douglascordeiro** [pistacheio/pistache#126]
There is any example showing how to get a json/xml/text body from a post request?

**Comment by jeffvandyke** [comment]
I'm using `request.body()` to get it as a `std::string`, and then I can use RapidJSON, or any other json library, to parse and use it.

**Comment by xoac** [comment]
I do exactly the same, but I use https://github.com/jonathonl/goodform. This json / msgpack lib really fit to pistache.
