### ISSUE TITLE
Bug: errno.h include

### ISSUE THREAD

**Issue by Finkman** [pistacheio/pistache#1267]
The workaround with the `pist_quote.h` is not working.

```
/repo/plugins/WebService/libs/pistache/src/common/pist_strerror_r.cc:19:10: fatal error: 'sys/(*__errno_location ()).h' file not found
#include PIST_QUOTE(PST_ERRNO_HDR)
         ^~~~~~~~~~~~~~~~~~~~~~~~~
/repo/plugins/WebService/libs/pistache/src/../include/pistache/pist_quote.h:16:25: note: expanded from macro 'PIST_QUOTE'
  #define PIST_QUOTE(x) PIST_Q(x)
                        ^~~~~~~~~
/repo/plugins/WebService/libs/pistache/src/../include/pistache/pist_quote.h:15:21: note: expanded from macro 'PIST_Q'
  #define PIST_Q(x) #x
                    ^~
<scratch space>:60:1: note: expanded from here
"sys/(*__errno_location ()).h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```

I'm compiling with clang++-16.

**Comment by dgreatwood** [comment]
Thanks for the report.

What OS are you compiling in? Are your host (compiling host) and target the same?

**Comment by Finkman** [comment]
It is a linux plattform. Build from scratch for cross-compiling. So, host and target are not the same.
Maybe worth noting is, that we do use the llvm-stl instead of gnu's implementation.

**Comment by Finkman** [comment]
When I do
```diff
-// Use #include PIST_QUOTE(PST_ERRNO_HDR)
+// Use #include PST_ERRNO_HDR
 #ifndef __linux__
 // pistache/pst_errno.h prevents mingw gcc's bad macro substitution on errno
 // Same issue with clang on macOS and gcc on OpenBSD
-#define PST_ERRNO_HDR pistache/pst_errno.h
+#define PST_ERRNO_HDR "pistache/pst_errno.h"
 #else
-#define PST_ERRNO_HDR sys/errno.h
+#define PST_ERRNO_HDR "sys/errno.h"
 #endif
```
and
```diff
-#include PIST_QUOTE(PST_ERRNO_HDR)
+#include PST_ERRNO_HDR
```


No issues anymore. Is there any sane reason you did it the way you did? Because, as far as I understood, strings are not subject of macro replacements.

**Comment by dgreatwood** [comment]
Given the issue with substitution of "errno" with errno's macro definition, this (making the quotes part of the PST_ERRNO_HDR definition) looks a good approach.

I'll review the specific PR, hopefully later today.

P.S. Building from scratch is/should be fine.
