### ISSUE TITLE
-lnet not found

### ISSUE THREAD

**Issue by hopplahop** [pistacheio/pistache#135]
when compiling, I get the following error:
/usr/bin/ld: cannot find -lnet

I have an Ubuntu system 16.04 64 bit
For installation I have used the following instruction: 
http://pistache.io/quickstart

Compiling problems caused by namespace Net I have solved by naming Net -> Pistache

**Comment by hopplahop** [comment]
got the problem instead of -lnet I have to use -lpistache

**Comment by xoac** [comment]
exactly, pistache changed namespace from `Net` to `Pistache` and library from `net` to `pistache`. See #109

**Comment by jeffvandyke** [comment]
This issue seems like it's closable.

**Comment by nikolaydimitrov** [comment]
It'll be nice to update the documentation..

**Comment by sandakith** [comment]
This is a common problem in examples too. I created a pull request [ca316d3](https://github.com/oktal/pistache/pull/165) to update the example.
