### ISSUE TITLE
ResponseStream does not support std::string

### ISSUE THREAD

**Issue by jakobs** [pistacheio/pistache#148]
When using the ResponseStream with an std::string object like so:

    std::string strResult = "foo";
    stream << strResult;

I get an error, which stems from a missing template specialisation for Size.
I can do:

    stream << strResult.c_str();

But the error message is not clear, and I would not have expected not being able to provide an std::string directly.

**Comment by oktal** [comment]
Hello. You are right, chunk-encoding relies on a specific `Size<T>` template specialization to retrieve the size of the chunk depending on the type you are currently streaming. `Size<std::string>` is currently not specialized, will fix.
