### ISSUE TITLE
error: ‘Net’ is not a namespace-name

### ISSUE THREAD

**Issue by cmpunches** [pistacheio/pistache#181]
Your examples and documentation refer to using a Net namespace and reference objects in that namespace but it's not actually included in your examples.

All of your documentation and examples seem to depend on this making all of them broken.

**Comment by cmpunches** [comment]
I was able to work around this by changing the namespace-name used from 'Net' to 'Pistache':

`#include "pistache/endpoint.h"

using namespace Pistache;

class HelloHandler : public Http::Handler {
public:

    HTTP_PROTOTYPE(HelloHandler)

    void onRequest(const Http::Request& request, Http::ResponseWriter response) {
        response.send(Http::Code::Ok, "Hello World");
    }
};

int main() {
    Address addr(Ipv4::any(), Port(9080));
    auto opts = Http::Endpoint::options().threads(1);

    Http::Endpoint server(addr);
    server.init(opts);
    server.setHandler(Http::make_handler<HelloHandler>());
    server.serve();

    server.shutdown();
}
`

**Comment by cmpunches** [comment]
This appears to be an undocumented namespace change, so the library is still technically usable with some guesswork.

**Comment by cmpunches** [comment]
Closing issue -- some of the examples have this accounted for already.  This is technically a docs and cleanup issue.

**Comment by jeffvandyke** [comment]
How long have the docs been out of date though? True, this is not a code issue, but the docs, and especially the examples, do need to be updated. Pull request #165 has an example fix, but it hasn't been merged in yet. I think this issue should be re-opened until it's fixed.

**Comment by cmpunches** [comment]
It would be preferrable not to use implicit namespaces in the code to be honest, as it makes it harder to read and navigate.  I would recommend using full class paths for everything in the examples and code at least so that there is no ambiguity about where those things exist.
