### ISSUE TITLE
Question: Proper way to perform logging on each request

### ISSUE THREAD

**Issue by milipili** [pistacheio/pistache#182]
Hi!

I am currently using `Rest::Request` for logging the incoming requests. However I have a few questions:

* How to get the remote ip?
* What would be the most reliable way to log the response body size?
* Does it exist any handler for doing it automatically at the end of each request (to log status code for example)

Maybe we could build a minimal example to log nginx/apache-like requests.

Thanks!

**Comment by midned** [comment]
To get client's IP if your server is behind nginx what I would do is add client's ip as a header (`proxy_set_header  X-Real-IP $remote_addr;`) and get it from `req.headers();`
