### ISSUE TITLE
Client shutdown : doesn't close socket

### ISSUE THREAD

**Issue by VishwanathPatil** [pistacheio/pistache#193]
client  class shutdown API provided doesn't close the socket , due to which I am unable to reconnect after shutting down

**Comment by xoac** [comment]
Dublicated #164 #178

**Comment by VishwanathPatil** [comment]
void
ConnectionPool::closeIdleConnections() {
	for(auto it = conns.begin(); it != conns.end(); ++it) {

		std::shared_ptr<Connection> conn = pickConnection(it->first);
	    conn->close();
		/* std::cout << *it; ... */
	}
}

calling this from client shutdown() is that ok ?
