### ISSUE TITLE
compilation error related to the fPIC flag

### ISSUE THREAD

**Issue by pablogh-2000** [pistacheio/pistache#218]
Dear all,

while linking my library against pistache, I got the following error:
```libpistache.a(http_headers.cc.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC```

In order to fix it, the only way I found was to add the following line to the main cmake:

```set(CMAKE_POSITION_INDEPENDENT_CODE ON)```

Could you please let me know if there is another way to fix this? Maybe I missed something in the compilation?

Thanks,

Pablo.

**Comment by xurxoham** [comment]
This may happen if you link a static library `.a` with a shared library `.so` or with a position independent code executable.
That option works, although you may be better interested in setting the variable via the command line interface instead:

    cmake /path/to/pistache -DCMAKE_POSITION_INDEPENDENT_CODE=ON

Another good alternative is to turn pistache into a shared library, which will be implicitly compiled with fPIC.
