### ISSUE TITLE
Request to update header files to better prevent namespace and header file name collisions

### ISSUE THREAD

**Issue by capablegh** [pistacheio/pistache#31]
This is a cool project, I like it!

Some minor requests if not already done or work in progress:

- Change the base namespace from "Net" to "pistache". Likely it would better prevent namespace
   collision with another project using "Net".
- In the header files change the includes for Pistache files to be '#include "pistache/..." This will likely
  prevent the include file name collisions if other projects happen to have a similar name.
- Renaming the libraries from libnet to libpistache would prevent potential library file name collisions..
- Add "-Wall" and "-Werror" to the compilation so that any warnings / errors can be identified and
  resolved.
- In example it could, arguably, be better so that all Pistache type names are fully qualified, or an
  alias be used.

**Comment by koallen** [comment]
I second it. Also, namespaces like `detail` in `flags.h` makes the compiler think it is ambiguous when I was using pistache together with some other libraries.

**Comment by oktal** [comment]
Makes sense, will do :+1:

**Comment by xoac** [comment]
I will also connect it with this [PR](https://github.com/oktal/pistache/pull/58). To change library name from `libnet` to `libpistache`.
@oktal  Really good work! Keep on.

**Comment by koallen** [comment]
Also, do we need to add the `_static` suffix to the static lib archive?

**Comment by xoac** [comment]
@koallen  In my opinion also no. There is information using extension `lib*.a`
@oktal  Do you have any special reason for that name? Maybe we miss sth?
