### ISSUE TITLE
Multiple issues with arm

### ISSUE THREAD

**Issue by Machinegon** [pistacheio/pistache#352]
Hi,

I've build pistache for ARM from this commit on master: adf5ce0eaca04cb8a71b241efb4b5a4f422ffb4f
CPU: armv7
g++ version: 6.2.0

I'm getting multiple issues when using the lib with ARM as described below, everything happens when calling: serve() or serverThreaded().
I tested all these cases on x86 64bits without problem:

x86 g++ version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

### Issue 1
First issue is a SEGFAULT when I'm compiling the hello_server example with optimization (-O2), without optimization it works.
Compilation command:
`$CXX hello_server.cc -Wextra -O2 -g -I /usr/include/pistache -lpistache -lpthread -o hello_server2`

Issue:
`Program received signal SIGSEGV, Segmentation fault.
0x00030426 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<void> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<void> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (__code=736201271,
    __k=..., __n=244143,
---Type <return> to continue, or q <return> to quit---`

### Issue 2
If I'm turning optimization off and going a litte further, I'm getting a floating point exception when changing from port 9080 to 8081.

Code:
`Pistache::Address addr(Pistache::Ipv4::any(), Pistache::Port(8081));
auto opts = Pistache::Http::Endpoint::options()
 .threads(1);
Http::Endpoint server(addr);
server.init(opts);
server.setHandler(this->_pcisController);
server.serve();`

Issue:
`Thread 1 "strapp" received signal SIGFPE, Arithmetic exception.
0x76f13ef6 in ?? () from /lib/libpthread.so.0
(gdb) backtrace
#0  0x76f13ef6 in ?? () from /lib/libpthread.so.0
#1  0x76f13058 in raise () from /lib/libpthread.so.0
#2  0x76d53b56 in __aeabi_ldiv0 () from /lib/libgcc_s.so.1
#3  0x00098866 in Pistache::Tcp::Listener::dispatchPeer (
    this=this@entry=0x7efff4f8, peer=...)
    at /home/machinegon/Libraries/pistache/src/server/listener.cc:344
#4  0x00098f00 in Pistache::Tcp::Listener::handleNewConnection (
    this=this@entry=0x7efff4f8)
    at /home/machinegon/Libraries/pistache/src/server/listener.cc:338
#5  0x0009903a in Pistache::Tcp::Listener::run (this=this@entry=0x7efff4f8)
    at /home/machinegon/Libraries/pistache/src/server/listener.cc:231
#6  0x000975a2 in Pistache::Http::Endpoint::serveImpl<void (Pistache::Tcp::Listener::*)()> (method=<optimized out>, this=0x7efff4f0)
    at /home/machinegon/Libraries/pistache/include/pistache/endpoint.h:72
#7  Pistache::Http::Endpoint::serve (this=0x7efff4f0)
    at /home/machinegon/Libraries/pistache/src/server/endpoint.cc:77
#8  0x00061b8a in STR::Application::initControllers (this=0x7efff644)
    at src/application.cpp:703
#9  0x00063db4 in STR::Application::Init (this=0x7efff644)
    at src/application.cpp:1767
#10 0x0006756a in main (argc=1, argv=0x7efffd74) at src/main.cpp:60`

### Issue 3
If I keep the port 9080 and optimization off and going a little further, I'm getting a malloc assertion when declaring the server endpoint on the heap.

Code:
`Pistache::Address addr(Pistache::Ipv4::any(), Pistache::Port(9080));
auto opts = Pistache::Http::Endpoint::options()
 .threads(1);
this->_endpoint = new Http::Endpoint(addr);
this->_endpoint->init(opts);
this->_endpoint->setHandler(this->_pcisController);
this->_endpoint->serve();`

Issue:
`strapp: malloc.c:2403: sysmalloc: Assertion (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Thread 1 "strapp" received signal SIGABRT, Aborted.
0x76c6d6b6 in ?? () from /lib/libc.so.6
(gdb) backtrace
#0  0x76c6d6b6 in ?? () from /lib/libc.so.6
#1  0x76c7b40c in raise () from /lib/libc.so.6
#2  0x76c7c0fa in abort () from /lib/libc.so.6
#3  0x76ca6b3a in ?? () from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)`

**Comment by Machinegon** [comment]
EDIT: If a roll back a month from now, there's no issues.

**Comment by Fylax** [comment]
Can you write down the commit you rolled back?
