### ISSUE TITLE
Undefined SOVERSION

### ISSUE THREAD

**Issue by DorfilIkatu** [pistacheio/pistache#357]
Hi, when building pistache as a shared library, I get a "libpistache.so.SOVERSION". In `src/CMakeLists.cmake` the `SOVERSION` variable takes the value of `GENERIC_LIB_SOVERSION` which is not defined anywhere. 
Could it be that the idea is to define this values in `PistacheTargets.cmake`? But I couldn't find how this file is generated.
Which would be the correct approach of defining the library version?

Thanks

**Comment by xurxoham** [comment]
I've solved this by modifying the `src/CMakeLists.txt` file. Specifically, I added the following
```
add_library(pistache SHARED ${SOURCE_FILES})
set_target_properties(pistache PROPERTIES
    NO_SONAME ON
    )
```

Another option is to set the `VERSION` attribute in the `project` command, in the root CMakeLists.txt:
```
project (pistache
    DESCRIPTION "A high-performance REST Toolkit written in C++"
    VERSION 0.0.1
    )
```
