### ISSUE TITLE
undefined reference to Net::Http::Endpoint::bind

### ISSUE THREAD

**Issue by nabilasalmi** [pistacheio/pistache#40]
Hi, 
I am new in using Pistache. I installed the latest version on a Debian 8.2 Jessie, and want to create a Rest server in a c++ application.
I followed the "Getting started", but i defined in a class a static member restServer of type  Http::Endpoint, then i bound this member with an address (using the bind method).
This is my code :
 
              ` static Http::Endpoint restServer;

                restServer.bind(addr);
		restServer.init(opts);
		restServer.setHandler(std::make_shared<RESTHandler>());
		restServer.serve();`

I added in my makefile the -lnet option so that to link with libnet library that i found installed after pistache installation. But, i got an error when linking : 
undefined reference to Net::Http::Endpoint::bind. 
I searched in endpoint.h and see that it defines the bind method, so what is the problem ?

Without using the bind method, it works well, but i need to use the static member so that i can stop the rest server whenever i want. 

Can anyone help me please ??

Thank you !

**Comment by oktal** [comment]
Hello,

Could you please provide your complete source code so that I can try locally ?

**Comment by nabilasalmi** [comment]
Hello,

Thank's for your reply !

This is my source code: 

`***********************************
RESTHandler.hxx
***********************************
#include "pistache/endpoint.h"
using namespace Net;
class RESTHandler : public Http::Handler
{
	private:
		
	public:
	    
		RESTHandler();
		~RESTHandler();
		
		HTTP_PROTOTYPE(RESTHandler)

		void onRequest(const Http::Request& request, Http::ResponseWriter response);
};

***********************************
RESTHandler.cxx
***********************************
#include "RESTHandler.hxx"
using namespace Net;
RESTHandler::RESTHandler() {}

RESTHandler::~RESTHandler() {}

void RESTHandler::onRequest(const Http::Request& request, Http::ResponseWriter response) 
{
	response.send(Http::Code::Ok, "Hello, World");
}

***********************************
MyProgram.hxx
***********************************
#include "RESTHandler.hxx"

using namespace Net;

class MyProgram
{
private:
	static Http::Endpoint restServer;
	
public:
    MyProgram();
    ~MyProgram();
	static bool launchRestServer();
	static bool stopRestServer();
	static void* restMainThread(void* params);
}

***********************************
MyProgram.cxx
***********************************
#include "MyProgram.hxx"
#include <iostream>

Http::Endpoint MyProgram::restServer;

MyProgram::MyProgram()
{
	launchRestServer();
}
MyProgram::~MyProgram()
{
	stopRestServer();	
}

void* MyProgram::restMainThread(void* params)
{
	char* restPort = (char*)params;
	auto opts = Http::Endpoint::options().threads(1);
	Net::Address addr(Net::Ipv4::any(), Net::Port(atoi(restPort)) );
	restServer.bind(addr);
	restServer.init(opts);
	restServer.setHandler(std::make_shared<RESTHandler>());
	restServer.serve();
	
}

bool MyProgram::launchRestServer()
{
	char restPort[5]="9080";
	cout << "Initializing a REST server on port " << restPort << endl;
	Thread* restThread = new Thread(); // Thread is a local class ...
	restThread->start(restMainThread, (void*)restPort );
	
	return true;
}

bool MyProgram::stopRestServer()
{
	restServer.shutdown();
}`

**Comment by Memnarch** [comment]
make shure you link against the static lib generated by the make files of pistache. Fixed it for me.

**Comment by abhi-infrrd** [comment]
@Memnarch How did you do it in makefiles?

**Comment by Memnarch** [comment]
Sorry, no clue :/
Not sure which one i used, but when you do your project using any kind of proper C++ IDE, you'll have configpages to add those static libs.. IIRC I just build the static lib using the makefiles

**Comment by RaboliotTheGrey** [comment]
(It's a but late :/)

I make it compile with this command (on Fedora 29): 
`g++ main.cpp -lpistache -pthread -o yourExecutable`

You just need to add those options to the linker in your makefile : `-lpistache -pthread`
