### ISSUE TITLE
integer optional is empty if its value is 1

### ISSUE THREAD

**Issue by migarma** [pistacheio/pistache#505]
this expression always returns true: Pistache::Optional<int32_t>(Pistache::Some(1)).isEmpty()

**Comment by migarma** [comment]
This issue cause all integer Pistache::Optional with 1 in its value returns it is empty.
The problem is this union, removing it may solve the problem.
`    union {
        uint8_t bytes[sizeof(T)];
        none_flag_t none_flag;
};`

**Comment by ecarrollcode** [comment]
This doesn't seem to reproducible off of `master` anymore. I have a PR up (https://github.com/oktal/pistache/pull/607) that adds test cases for `Pistache::Optional<int32_t>` which pass locally for me.
