### ISSUE TITLE
Does Pistache support '206/Partial Content' response?

### ISSUE THREAD

**Issue by jsignoret** [pistacheio/pistache#526]
Dear all,

Answering to GET request, my rest api may have to return potentially huge content. I wonder if I can use the code 206/Partial content to return several limited data (json formatted) instead of only one big flow. Does Pistache handle this code? If yes I suppose that I have to finish with the OK code...

Many thanks for any help.
Jacqueline

**Comment by hydratim** [comment]
It is defined in https://github.com/oktal/pistache/blob/master/include/pistache/http_defs.h so it should work, but I've not personally tested it - so I'm not sure.

The response line should look something like: 
`response.send(Http::Code::Partial_Content, my_response_string)
