### ISSUE TITLE
Crash in Pistache while API was being invoked

### ISSUE THREAD

**Issue by tmustafa** [pistacheio/pistache#553]
Here is the stack trace of the crashing thread. Sorry, I mentioned something incorrect earlier, its exception due to throw from "epoll_ctl".

Using conanized Pistache and here is the version number "pistache/2019.05.29".

Maybe this is a known problem, I tried to search but did not find any similar issue.

Any feedback will be appreciated.

(gdb) bt
#0  0x00007f233403de97 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f233403f801 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f2334a3ab52 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f2334a38a06 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f2334a38a41 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f2334a38c74 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000563afa5a3f72 in Pistache::Polling::Epoll::rearmFd (this=<optimized out>, fd=<optimized out>, interest=..., tag=..., mode=<optimized out>)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/os.cc:187
#7  0x0000563afa5a6f75 in Pistache::Aio::AsyncImpl::dispatchCall<void (Pistache::Aio::SyncImpl::*)(Pistache::Aio::Reactor::Key const&, int, Pistache::Polling::NotifyOn, Pistache::Polling::Tag, Pistache::Polling::Mode), int&, Pistache::Polling::NotifyOn&, Pistache::Polling::Tag&, Pistache::Polling::Mode&> (
    func=&virtual Pistache::Aio::SyncImpl::modifyFd(Pistache::Aio::Reactor::Key const&, int, Pistache::Polling::NotifyOn, Pistache::Polling::Tag, Pistache::Polling::Mode), key=..., this=<optimized out>)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/reactor.cc:450
#8  Pistache::Aio::AsyncImpl::modifyFd (this=<optimized out>, key=..., fd=70, interest=Pistache::Polling::NotifyOn::Read, tag=..., 
    mode=Pistache::Polling::Mode::Edge)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/reactor.cc:410
#9  0x0000563afa574256 in Pistache::Tcp::Transport::<lambda()>::operator() (__closure=<synthetic pointer>)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/transport.cc:229
#10 Pistache::Tcp::Transport::asyncWriteImpl (this=this@entry=0x563afc3196d0, fd=fd@entry=70)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/transport.cc:273
#11 0x0000563afa576885 in Pistache::Tcp::Transport::onReady (this=0x563afc3196d0, fds=...)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/transport.cc:110
#12 0x0000563afa5a8bcb in Pistache::Aio::SyncImpl::handleFds (events=..., this=0x563c02575600)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/reactor.cc:186
#13 Pistache::Aio::SyncImpl::runOnce (this=0x563c02575600)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/reactor.cc:148
#14 0x0000563afa5a6a99 in Pistache::Aio::SyncImpl::run (this=<optimized out>)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/reactor.cc:159
#15 Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1}::operator()() const (__closure=<optimized out>)
    at /root/.conan/data/pistache/2019.05.29/oss/testing/build/aa10c32850b15ef5456122906d38ebd7c80ab68c/source_subdir/src/common/reactor.cc:468
#16 std::__invoke_impl<void, Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1}>(std::__invoke_other, Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1}&&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#17 std::__invoke<Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1}>(std::__invoke_result&&, (Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1}&&)...) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#18 std::thread::_Invoker<std::tuple<Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=<optimized out>)
    at /usr/include/c++/7/thread:234
#19 std::thread::_Invoker<std::tuple<Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1}> >::operator()() (this=<optimized out>)
    at /usr/include/c++/7/thread:243
#20 std::thread::_State_impl<std::thread::_Invoker<std::tuple<Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1}> > >::_M_run() (this=<optimized out>)
    at /usr/include/c++/7/thread:186
#21 0x00007f2334a6357f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#22 0x00007f2334d366db in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#23 0x00007f233412088f in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by tmustafa** [comment]
From the sources, here is where the crash is happening:

   void
    Epoll::rearmFd(Fd fd, Flags<NotifyOn> interest, Tag tag, Mode mode) {
        struct epoll_event ev;
        ev.events = toEpollEvents(interest);
        if (mode == Mode::Edge)
            ev.events |= EPOLLET;
        ev.data.u64 = tag.value_;

        TRY(epoll_ctl(epoll_fd, EPOLL_CTL_MOD, fd, &ev));       <--------***
    }

**Comment by mohsenomidi** [comment]
@tmustafa 

would you please provide the steps to reproduce this error ?

sample code could be useful
