### ISSUE TITLE
libpistache-dev stable is missing from ppa:kip/pistache

### ISSUE THREAD

**Issue by nickaein** [pistacheio/pistache#567]
Installing stable packages with:

```
$ sudo add-apt-repository ppa:kip/pistache
$ sudo apt update
$ sudo apt install libpistache-dev
```

fails with the following error:
```
E: Unable to locate package libpistache-dev
```

It seems the binary packages are missing from the ppa repo:

http://ppa.launchpad.net/kip/pistache/ubuntu/pool/main/p/pistache/

and only unstable packages are available:

http://ppa.launchpad.net/kip/pistache-unstable/ubuntu/pool/main/p/pistache/

**Comment by kiplingw** [comment]
Hey @nickaein. You are correct. At this time @dennisjenkins75 and I haven't released a stable package yet. As soon as we do the stable PPA will have binaries published. In the mean time the next best thing are the unstable packages which are built from git head.

**Comment by ishandrov** [comment]
None of your installation instruction works, what a waste of time!

**Comment by Andy-Baxman** [comment]
Same issue with the unstable packages.

I do:

$ sudo add-apt-repository ppa:pistache+team/unstable
$ sudo apt update
$ sudo apt install libpistache-dev

I get:

E: Unable to locate package libpistache-dev

This is on Ubuntu 18.04

**Comment by kiplingw** [comment]
Hey @andixlm. Unfortunately we don't support Bionic (18.04) because the packages we depend weren't available. I recommend you consider upgrading to Groovy (20.10).

**Comment by andixlm** [comment]
Hi @kiplingw
I think I'm not that one person you'd like to mention. The issue subject is completely unfamiliar to me :)

**Comment by kiplingw** [comment]
Sorry, my bad. I meant @Andy-Baxman.
