### ISSUE TITLE
compile for arm64 

### ISSUE THREAD

**Issue by annnhj** [pistacheio/pistache#618]
Hi, guys. can anyone explain how to compile pistache for arm64. 
I saw the instructions buy it wasn't very clear. tks

**Comment by kiplingw** [comment]
Hey @annnhj. To compile from source it is the same as on any other supported architecture. There are currently pre-compiled binaries for arm64 on the unstable [PPA](https://launchpad.net/%7Ekip/+archive/ubuntu/pistache-unstable) so there is no need to waste time trying to do it yourself unless you need to modify the source.
