### ISSUE TITLE
Code doesn't compile anymore for C++11

### ISSUE THREAD

**Issue by yvesdm3000** [pistacheio/pistache#634]
Hi,

Due to commit d72ee8c7 it no longer compiles for C++11.
std::equal(it.begin(), it.end(), it2.begin(), it2.end(), [](a,b){})   is supported on C++14 onwards...
Only the version with 4 parameters (without it2.end()) is supported on C++11.

Yves

**Comment by young-seoulrobotics** [comment]
I met the same error, and the problem is that CMakeLists.txt in the root directory uses C++14/C++17 depending on the compiler version.

**Comment by ivan1993br** [comment]
So this library will not be c++11 compatible?

**Comment by yvesdm3000** [comment]
> 
> 
> So this library will not be c++11 compatible?

That's correct, but a small change for the "std::equal" code and it compiles again for C++11

Yves

**Comment by kiplingw** [comment]
@yvesdm3000, if you'd like to submit and test that patch, we can get that into mainline for you.

**Comment by mohsenomidi** [comment]
this issue can be closed.
if the pull request or changes exists, we can discuss in that thread for now the Pistache will compiled on >= C++14
