### ISSUE TITLE
Poor performance. Errors like Unable to connect to 0.0.0.0:9080 Cannot assign requested address

### ISSUE THREAD

**Issue by vankofalcon** [pistacheio/pistache#635]
Hi folks, I'm testing pistache under load but I'm getting poor results :( 
I see some socket errors of that kind `Unable to connect to 0.0.0.0:9080 Cannot assign requested address`
Here it's the code I'm running on Linux
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

#include "pistache/endpoint.h"
#include "include/rapidjson/document.h"
#include "include/rapidjson/stringbuffer.h"
#include "include/rapidjson/prettywriter.h"

using namespace std;
using namespace rapidjson;
using namespace Pistache;

class HelloHandler : public Http::Handler {
public:

HTTP_PROTOTYPE(HelloHandler)

  void onRequest(const Http::Request &request, Http::ResponseWriter response) override {
        UNUSED(request);

        auto body = generateResponse();
        response.send(Pistache::Http::Code::Ok, body);
    }

    const std::string generateResponse() const {
        Document d;
        d.SetObject();
        d.AddMember("id", std::chrono::system_clock::now().time_since_epoch().count(), d.GetAllocator());
        d.AddMember("name", "test", d.GetAllocator());
        StringBuffer sb;
        PrettyWriter<StringBuffer> writer(sb);
        d.Accept(writer);
        return std::string(sb.GetString());
    }
};

int main() {
    const Port &port = Pistache::Port(9080);
    Pistache::Address addr(Pistache::Ipv4::any(), port);
    auto opts = Pistache::Http::Endpoint::options()
            .threads(8)
            .flags(Tcp::Options::ReuseAddr);;

    Http::Endpoint server(addr);
    server.init(opts);
    server.setHandler(Http::make_handler<HelloHandler>());
    server.serve();
}

And running the test with:

wrk -t8 -c20 -d15 -R100000 http://0.0.0.0:9080

And the output from the test:

Running 15s test @ http://0.0.0.0:9080
  8 threads and 20 connections
  Thread calibration: mean lat.: 1533.635ms, rate sampling interval: 9379ms
  Thread calibration: mean lat.: 1531.476ms, rate sampling interval: 9428ms
  Thread calibration: mean lat.: 1528.567ms, rate sampling interval: 9215ms
  Thread calibration: mean lat.: 1512.422ms, rate sampling interval: 9306ms
  Thread calibration: mean lat.: 1556.204ms, rate sampling interval: 9404ms
  Thread calibration: mean lat.: 1551.005ms, rate sampling interval: 9404ms
  Thread calibration: mean lat.: 1500.594ms, rate sampling interval: 9281ms
  Thread calibration: mean lat.: 1564.329ms, rate sampling interval: 9404ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     -nanus    -nanus   0.00us    0.00%
    Req/Sec       -nan      -nan   0.00      0.00%
  28229 requests in 16.02s, 2.99MB read
  Socket errors: connect 16, read 0, write 0, timeout 64
Requests/sec:   1761.79
Transfer/sec:    190.98KB

As you can see there are some errors `Socket errors: connect 16, read 0, write 0, timeout 64`
and the r/s rate is so low - only 1761 :(

When I test a dummy java rest api which is doing exactly the same the r/s is much higher ~ 46255 r/s and with zero socket errors. I refuse to believe that c++ is performing so bad. 
Can you please help me fix that?

P.S. Sorry for the bad code formatting

**Comment by vankofalcon** [comment]
Btw I experience the same socket errors when testing with https://github.com/rakyll/hey. So it's not just the wrk tool

**Comment by mohsenomidi** [comment]
@vankofalcon 

These are my benchmark tests with your provided sample, in different duration:
in 1 second tests we have good performance, errors occurs only on higher test duration, 
i can not reproduce the timeout error, just get the connection error... 

could you please describe your expectation in detail ?
do you have a benchmark with other libraries behavior ? 

```
./wrk -t20 -c400 -d1s  http://127.0.0.1:9080

Running 1s test @ http://127.0.0.1:9080
  20 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.39ms   12.84ms 225.04ms   93.74%
    Req/Sec   847.21      1.23k    6.71k    86.24%
  16420 requests in 1.10s, 1.74MB read
Requests/sec:  14914.28
Transfer/sec:      1.58MB
```
```
./wrk -t20 -c400 -d2s  http://127.0.0.1:9080

Running 2s test @ http://127.0.0.1:9080
  20 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.98ms   24.79ms 460.68ms   88.67%
    Req/Sec   559.14    811.94     4.22k    87.50%
  20200 requests in 2.10s, 2.14MB read
Requests/sec:   9623.26
Transfer/sec:      1.02MB
```
```
./wrk -t20 -c400 -d15  http://127.0.0.1:9080

Running 15s test @ http://127.0.0.1:9080
  20 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.60ms   18.82ms 420.29ms   87.51%
    Req/Sec   372.79    686.47     8.70k    92.23%
  28230 requests in 15.10s, 2.99MB read
  Socket errors: connect 400, read 0, write 0, timeout 0
Requests/sec:   1869.77
Transfer/sec:    202.68KB
```

```
./wrk -t20 -c400 -d2m  http://127.0.0.1:9080
Running 2m test @ http://127.0.0.1:9080
  20 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    18.67ms   24.31ms 252.27ms   85.49%
    Req/Sec   380.78    533.09     3.78k    90.06%
  28230 requests in 2.00m, 2.99MB read
  Socket errors: connect 400, read 0, write 0, timeout 0
Requests/sec:    235.06
Transfer/sec:     25.48KB

```
```
Sample Code Thread changed to 50

./wrk -t8 -c20 -d15  http://127.0.0.1:9080

Running 15s test @ http://127.0.0.1:9080
  8 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   835.99us    1.03ms   6.89ms   75.14%
    Req/Sec   719.28      1.04k    5.80k    92.09%
  28230 requests in 15.08s, 2.99MB read
  Socket errors: connect 16, read 0, write 0, timeout 0
Requests/sec:   1872.55
Transfer/sec:    202.98KB

```

```
Sample Code Thread changed to 100

./wrk -t8 -c20 -d15  http://127.0.0.1:9080

Running 15s test @ http://127.0.0.1:9080
  8 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   838.22us    0.97ms   7.17ms   75.25%
    Req/Sec   733.67      0.98k    5.27k    89.58%
  28230 requests in 15.08s, 2.99MB read
  Socket errors: connect 16, read 0, write 0, timeout 0
Requests/sec:   1872.44
Transfer/sec:    202.97KB
```
```
Sample Code Thread changed to 100

./wrk -t8 -c20 -d1s  http://127.0.0.1:9080

Running 1s test @ http://127.0.0.1:9080
  8 threads and 20 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   648.10us  631.47us   6.93ms   92.20%
    Req/Sec     1.91k     1.41k    4.63k    40.00%
  15252 requests in 1.01s, 1.61MB read
Requests/sec:  15113.16
Transfer/sec:      1.60MB
```
