### ISSUE TITLE
Compilation Problem : No Matching function

### ISSUE THREAD

**Issue by danishmarif** [pistacheio/pistache#664]
Hi , I recently cloned the new Pistache project and I keep getting this error when I try to compile the project with pictache

Error: no matching function for call to ‘equal(std::basic_string<char>::const_iterator, std::basic_string<char>::const_iterator, std::basic_string<char>::const_iterator, std::basic_string<char>::const_iterator, Pistache::Http::Header::LowercaseEqual::operator()(const string&, const string&) const::<lambda(const char&, const char&)>)’
             });
              ^	RestClientTest	C:\usr\local\include\pistache\http_headers.h	38	

Kindly look into this.

Moreover , is there any example for implementing HTTPS based server using pistache?

**Comment by mohsenomidi** [comment]
The Pistache must be compiled under C++14 , it seems you are using older version of C++

**Comment by danishmarif** [comment]
So which is last stable version I can use for c++11 compatible?
And are there any examples regarding HTTPS server?

**Comment by mohsenomidi** [comment]
There is no longer support for c++11, and also there is no stable version yet.
You can find examples in example & test directories
