### ISSUE TITLE
How can I make the project in c++11

### ISSUE THREAD

**Issue by lifeibin** [pistacheio/pistache#730]
I have a problem. The newest version needs to be maked in C++17, but my gcc version only just support c++11, how can I install the project in c++11. And this project has no release version.

**Comment by ywiyogo** [comment]
See https://github.com/oktal/pistache/issues/634 or install the newer gcc manually in your system, at least gcc 5.4

**Comment by lifeibin** [comment]
> See #634 or install the newer gcc manually in your system, at least gcc 5.4

ok, thanks a lot. I will upgrade the gcc to use pistache.
