### ISSUE TITLE
Endpoint:useSSL

### ISSUE THREAD

**Issue by gdani2c4** [pistacheio/pistache#744]
I don't see in the user's guide reference to this - maybe in other documentation? If not, should this method function with a valid SSL certificate?

**Comment by kiplingw** [comment]
The documentation is very old and it needs to be updated. If you'd like to consider doing this, it would be appreciated.

**Comment by gdani2c4** [comment]
@kiplingw first step, I'll consider to test it. if yes: next step: report results,  consider to update documentation. note: my level of experience: almost 0
