### ISSUE TITLE
E: Failed to fetch http://ppa.launchpad.net/pistache+team/stable/ubuntu/dists/focal/InRelease  403  Forbidden [IP: 91.189.95.83 80]

### ISSUE THREAD

**Issue by desjare** [pistacheio/pistache#790]
apt update failed on the ppa

**Comment by kiplingw** [comment]
Thanks @desjare. I am not able to replicate. Is this still occurring?

**Comment by desjare** [comment]
Ubuntu 20.04

**Comment by kiplingw** [comment]
I am also running Focal and I don't see this problem.

**Comment by desjare** [comment]
I’m on Linux on win. Sorry for the fuss will try on my personal machine
tonight.

Have a nice one
Éric
