### ISSUE TITLE
Json in query doesn't work

### ISSUE THREAD

**Issue by hafizhussainh** [pistacheio/pistache#80]
I was trying the client method, it works with normal url and query.

eg: localhost:8083/myservice?data=xyz

But if I give json value to data in the query, it does not generate a request.

Should I add any json parser before constructing the query string? Please let me know, what I am missing

**Comment by jeffvandyke** [comment]
This might not be pistache specific, but characters like '{' or '}', or ':', or '"' are supported in url's. You can see the "Unreserved Characters" section of http://www.ietf.org/rfc/rfc3986.txt for the official spec. AFAIK, json is usually sent in the body of a POST request to servers, or if it must be in the url, it could be escaped and properly encoded.

**Comment by hafizhussainh** [comment]
In post method also i tried this.

string myson = "{ .. }"

auto resp = client.post(page).body(myjson).send();

I am getting the request, but body is empty. Is the syntax correct?

**Comment by jeffvandyke** [comment]
That does look correct, provided string is std::string, I'm not sure on this one. Maybe if it's still unsolved I could take a closer look sometime this week.

**Comment by hafizhussainh** [comment]
It works, but I'm getting empty JSON on server side. Looks like I should add headers "application/json".

I tried this. 

auto resp = client.headers.add("content-type": "application/xml").post(page).body(myjson).send();

But didn't work. Please let me know the correct syntax of this also.

**Comment by oktal** [comment]
Hello,

Yes, you can try adding the Content-Type header. Actually, json values are plain old `string`s, which means that Pistache can not really know that your body is json-encoded unless it parses it, which it does not.

Something along those lines should work:

```cpp
auto resp = client.post(page).header(std::make_shared<Http::Header::ContentType>(MIME(Application, Json)).body(myjson).send();
```

**Comment by oktal** [comment]
Hello,

What's the state of this issue ?

**Comment by nelsonhf** [comment]
I have a similar problem. Check that your client is sending "Content-Length" and not "content-length".
Headers should be case insensitive. This is issue #86
