### ISSUE TITLE
Many errors when compiling C++ example using pistache.

### ISSUE THREAD

**Issue by jstechg** [pistacheio/pistache#824]
I just installed pistache on Ubuntu Mate linux, following the steps indicated in the section "Installing Pistache" of the website "http://pistache.io/quickstart".

And I am trying to compile a simple example, which I have copied from "https://github.com/oktal/pistache/blob/master/examples/hello_server.cc"

The version of g ++ I use is:

    $ g ++ --version
    g ++ (Ubuntu 7.5.0-3ubuntu1 ~ 18.04) 7.5.0
    Copyright (C) 2017 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions. There is NO
   warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I compile it with the command:

    g ++ -lpistache pistacheExample01.cpp

And I get these errors which I show below.

I don't see what I'm doing wrong and I appreciate any help.

COMPILER OUTPUT:

    /tmp/ccWl4qRb.o: En la función `main':
    pistacheEj01.cpp:(.text+0x14c): referencia a `Pistache::Port::Port(unsigned short)' sin definir
    pistacheEj01.cpp:(.text+0x15b): referencia a `Pistache::IP::any()' sin definir
    pistacheEj01.cpp:(.text+0x1ad): referencia a `Pistache::Address::Address(Pistache::IP, Pistache::Port)' sin definir
    pistacheEj01.cpp:(.text+0x1c0): referencia a `Pistache::Http::Endpoint::options()' sin definir
    pistacheEj01.cpp:(.text+0x1d4): referencia a `Pistache::Http::Endpoint::Options::threads(int)' sin definir
    pistacheEj01.cpp:(.text+0x211): referencia a `Pistache::Http::Endpoint::Endpoint(Pistache::Address const&)' sin definir
    pistacheEj01.cpp:(.text+0x22a): referencia a `Pistache::Http::Endpoint::init(Pistache::Http::Endpoint::Options const&)' sin definir
    pistacheEj01.cpp:(.text+0x26b): referencia a `Pistache::Http::Endpoint::setHandler(std::shared_ptr<Pistache::Http::Handler> const&)' sin definir
    pistacheEj01.cpp:(.text+0x298): referencia a `Pistache::Http::Endpoint::serve()' sin definir
/tmp/ccWl4qRb.o: En la función `Pistache::Http::Handler::~Handler()':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerD2Ev[_ZN8Pistache4Http7HandlerD5Ev]+0xf): referencia a `vtable for Pistache::Http::Handler' sin definir
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerD2Ev[_ZN8Pistache4Http7HandlerD5Ev]+0x22): referencia a `Pistache::Tcp::Handler::~Handler()' sin definir
/tmp/ccWl4qRb.o: En la función `Pistache::Http::Endpoint::~Endpoint()':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http8EndpointD2Ev[_ZN8Pistache4Http8EndpointD5Ev]+0x2a): referencia a `Pistache::Tcp::Listener::~Listener()' sin definir
    /tmp/ccWl4qRb.o: En la función `Pistache::Async::Promise<long> Pistache::Http::ResponseWriter::send<13ul>(Pistache::Http::Code, char const (&) [13ul], Pistache::Http::Mime::MediaType const&)':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http14ResponseWriter4sendILm13EEENS_5Async7PromiseIlEENS0_4CodeERAT__KcRKNS0_4Mime9MediaTypeE[_ZN8Pistache4Http14ResponseWriter4sendILm13EEENS_5Async7PromiseIlEENS0_4CodeERAT__KcRKNS0_4Mime9MediaTypeE]+0x4a): referencia a `Pistache::Http::ResponseWriter::sendImpl(Pistache::Http::Code, char const*, unsigned long, Pistache::Http::Mime::MediaType const&)' sin definir
    /tmp/ccWl4qRb.o: En la función `Pistache::Tcp::Handler::Handler(Pistache::Tcp::Handler const&)':
    pistacheEj01.cpp:(.text._ZN8Pistache3Tcp7HandlerC2ERKS1_[_ZN8Pistache3Tcp7HandlerC5ERKS1_]+0x26): referencia a `vtable for Pistache::Tcp::Handler' sin definir
    /tmp/ccWl4qRb.o: En la función `Pistache::Http::Handler::Handler(Pistache::Http::Handler const&)':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerC2ERKS1_[_ZN8Pistache4Http7HandlerC5ERKS1_]+0x26): referencia a `vtable for Pistache::Http::Handler' sin definir
    /tmp/ccWl4qRb.o: En la función `Pistache::Http::Handler::Handler()':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerC2Ev[_ZN8Pistache4Http7HandlerC5Ev]+0x14): referencia a `Pistache::Tcp::Handler::Handler()' sin definir
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerC2Ev[_ZN8Pistache4Http7HandlerC5Ev]+0x1b): referencia a `vtable for Pistache::Http::Handler' sin definir
    /tmp/ccWl4qRb.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x28): referencia a `Pistache::Http::Handler::onInput(char const*, unsigned long, std::shared_ptr<Pistache::Tcp::Peer> const&)' sin definir
    /tmp/ccWl4qRb.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x30): referencia a `Pistache::Http::Handler::onConnection(std::shared_ptr<Pistache::Tcp::Peer> const&)' sin definir
    /tmp/ccWl4qRb.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x38): referencia a `Pistache::Http::Handler::onDisconnection(std::shared_ptr<Pistache::Tcp::Peer> const&)' sin definir
    /tmp/ccWl4qRb.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x48): referencia a `Pistache::Http::Handler::onTimeout(Pistache::Http::Request const&, Pistache::Http::ResponseWriter)' sin definir
    /tmp/ccWl4qRb.o:(.data.rel.ro._ZTI12HelloHandler[_ZTI12HelloHandler]+0x10): referencia a `typeinfo for Pistache::Http::Handler' sin definir
    collect2: error: ld returned 1 exit status
    jsf@jsf-VirtualBox:~/pistache$ g++ -lpistache pistacheEj01.cpp
    /tmp/cc5mBJYN.o: En la función `main':
    pistacheEj01.cpp:(.text+0x14c): referencia a `Pistache::Port::Port(unsigned short)' sin definir
    pistacheEj01.cpp:(.text+0x15b): referencia a `Pistache::IP::any()' sin definir
    pistacheEj01.cpp:(.text+0x1ad): referencia a `Pistache::Address::Address(Pistache::IP, Pistache::Port)' sin definir
    pistacheEj01.cpp:(.text+0x1c0): referencia a `Pistache::Http::Endpoint::options()' sin definir
    pistacheEj01.cpp:(.text+0x1d4): referencia a `Pistache::Http::Endpoint::Options::threads(int)' sin definir
    pistacheEj01.cpp:(.text+0x211): referencia a `Pistache::Http::Endpoint::Endpoint(Pistache::Address const&)' sin definir
    pistacheEj01.cpp:(.text+0x22a): referencia a `Pistache::Http::Endpoint::init(Pistache::Http::Endpoint::Options const&)' sin definir
    pistacheEj01.cpp:(.text+0x26b): referencia a `Pistache::Http::Endpoint::setHandler(std::shared_ptr<Pistache::Http::Handler> const&)' sin definir
    pistacheEj01.cpp:(.text+0x298): referencia a `Pistache::Http::Endpoint::serve()' sin definir
    /tmp/cc5mBJYN.o: En la función `Pistache::Http::Handler::~Handler()':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerD2Ev[_ZN8Pistache4Http7HandlerD5Ev]+0xf): referencia a `vtable for Pistache::Http::Handler' sin definir
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerD2Ev[_ZN8Pistache4Http7HandlerD5Ev]+0x22): referencia a `Pistache::Tcp::Handler::~Handler()' sin definir
    /tmp/cc5mBJYN.o: En la función `Pistache::Http::Endpoint::~Endpoint()':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http8EndpointD2Ev[_ZN8Pistache4Http8EndpointD5Ev]+0x2a): referencia a `Pistache::Tcp::Listener::~Listener()' sin definir
    /tmp/cc5mBJYN.o: En la función `Pistache::Async::Promise<long> Pistache::Http::ResponseWriter::send<13ul>(Pistache::Http::Code, char const (&) [13ul], Pistache::Http::Mime::MediaType const&)':
pistacheEj01.cpp:(.text._ZN8Pistache4Http14ResponseWriter4sendILm13EEENS_5Async7PromiseIlEENS0_4CodeERAT__KcRKNS0_4Mime9MediaTypeE[_ZN8Pistache4Http14ResponseWriter4sendILm13EEENS_5Async7PromiseIlEENS0_4CodeERAT__KcRKNS0_4Mime9MediaTypeE]+0x4a): referencia a `Pistache::Http::ResponseWriter::sendImpl(Pistache::Http::Code, char const*, unsigned long, Pistache::Http::Mime::MediaType const&)' sin definir
    /tmp/cc5mBJYN.o: En la función `Pistache::Tcp::Handler::Handler(Pistache::Tcp::Handler const&)':
    pistacheEj01.cpp:(.text._ZN8Pistache3Tcp7HandlerC2ERKS1_[_ZN8Pistache3Tcp7HandlerC5ERKS1_]+0x26): referencia a `vtable for Pistache::Tcp::Handler' sin definir
    /tmp/cc5mBJYN.o: En la función `Pistache::Http::Handler::Handler(Pistache::Http::Handler const&)':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerC2ERKS1_[_ZN8Pistache4Http7HandlerC5ERKS1_]+0x26): referencia a `vtable for Pistache::Http::Handler' sin definir
    /tmp/cc5mBJYN.o: En la función `Pistache::Http::Handler::Handler()':
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerC2Ev[_ZN8Pistache4Http7HandlerC5Ev]+0x14): referencia a `Pistache::Tcp::Handler::Handler()' sin definir
    pistacheEj01.cpp:(.text._ZN8Pistache4Http7HandlerC2Ev[_ZN8Pistache4Http7HandlerC5Ev]+0x1b): referencia a `vtable for Pistache::Http::Handler' sin definir
    /tmp/cc5mBJYN.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x28): referencia a `Pistache::Http::Handler::onInput(char const*, unsigned long, std::shared_ptr<Pistache::Tcp::Peer> const&)' sin definir
    /tmp/cc5mBJYN.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x30): referencia a `Pistache::Http::Handler::onConnection(std::shared_ptr<Pistache::Tcp::Peer> const&)' sin definir
    /tmp/cc5mBJYN.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x38): referencia a `Pistache::Http::Handler::onDisconnection(std::shared_ptr<Pistache::Tcp::Peer> const&)' sin definir
    /tmp/cc5mBJYN.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x48): referencia a `Pistache::Http::Handler::onTimeout(Pistache::Http::Request const&, Pistache::Http::ResponseWriter)' sin definir
    /tmp/cc5mBJYN.o:(.data.rel.ro._ZTI12HelloHandler[_ZTI12HelloHandler]+0x10): referencia a `typeinfo for Pistache::Http::Handler' sin definir
    collect2: error: ld returned 1 exit status

**Comment by jstechg** [comment]
SOLVED: 

When executing g++ the library that needs symbols must be first, then the library that resolves the symbol.

So, I have recompiled it like this:
    g++ pistacheEj01.cpp -lpistache -lpthread -o pistacheEj01

And now it compiles correctly.

**Comment by kiplingw** [comment]
@jstechg, for now please don't use the website. It hasn't been updated in years. Please rely on the `README.md`. I'd recommend trying the PPA first with the prebuilt binaries instead of building it yourself (unless you are preparing a patch).
