### ISSUE TITLE
libpistache.so link file missing form shared library install

### ISSUE THREAD

**Issue by sky1902** [pistacheio/pistache#830]
Building pistache from source results in shared libraries with following names in install directory

rwxrwxrwx 1 root root      38 Sep 17  2019 /usr/lib/libpistache-0.0.002-git20200802.so -> libpistache-0.0.002-git20200802.so.0.0
-rw-r--r-- 1 root root 1116936 Sep 17  2019 /usr/lib/libpistache-0.0.002-git20200802.so.0.0
-rw-r--r-- 1 root root 2826330 Sep 17  2019 /usr/lib/libpistache.a

Used the following cmake command:

user@machine:~/pistache/pistache/build# cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DPISTACHE_BUILD_EXAMPLES=false -DPISTACHE_BUILD_TESTS=true -DPISTACHE_BUILD_DOCS=false -DPISTACHE_USE_SSL=false -DBUILD_SHARED_LIBS=true ..

We need a symlink from libpistache.so to libpistache-0.0.002-git20200802.so, for this to correctly install. 

I am wandering if this is a issue or is it a requirement to have the shared libraries named as above due to some reason??

**Comment by kiplingw** [comment]
Hey @sky1902. Please take a look at our section on interface versioning in the [readme](https://github.com/pistacheio/pistache#interface-versioning) and let us know if you still have questions.

**Comment by sky1902** [comment]
Do you think its better to manually create a symlink if I need to use -lpistache (I cannot use pistache-0.0.002-git20200802). Or do we have a option to disable version string as part of soname (editing the source is not an option for me)??

**Comment by kiplingw** [comment]
Hey @sky1902. There's no need for an additional alias. You should never be manually specifying a library's linker flags in your build environment. You should be using `pkg-config`, otherwise your environment will eventually break.

**Comment by sky1902** [comment]
Sure. Thank you.
