### ISSUE TITLE
GitHub Pages site points to the wrong branch

### ISSUE THREAD

**Issue by Tachi107** [pistacheio/pistache#862]
I think that [pistache.io](https://pistache.io) hosts the `gh-pages` branch of the repo, thus rendering useless changes to `index.html` in the main branch (commit 8f278dbd345b818740f865623d5039e9314352fd).
As a temporary solution, the GitHub Pages site should be built from the `master` branch, and the `gh-pages` one should be deleted. This is a GitHub setting, and I can't submit a pull request to fix it.
![image](https://user-images.githubusercontent.com/34214253/106937550-2e654280-671e-11eb-9971-47faba3121c2.png)

Looking at the site and the source, it seems that the web page was generated by Jekyll, but I can't find the Markdown(?) files used to generate it. In my opinion the ideal solution would be to have a CI/CD automatically generate html files from Markdown (or similar) files stored in a `web/` or in the `docs/` folder on every commit, and push those files to a `gh-pages` branch containing only the generated site sources.

**Comment by oktal** [comment]
Hello,

You are right, the current website is hosted by the `gh-pages` branch of the main repo.

This repo is still an ongoing work. I wanted to replace Jekyll by sometehing like docusaurus.

Having the CI automatically build and generate the site from the sources is definetely something that we'll want to setup.
You are more than welcome to help on that (making a new version of the website with docusaurus, setup-ing the CI correctly)

**Comment by Tachi107** [comment]
I'll have a look at docsaurus, I've never heard of it. Thanks

**Comment by Tachi107** [comment]
I'm currently fiddling around with docusaurus, and it seems very good! 
Do you have an SVG version of [assets/images/logo.png](https://github.com/pistacheio/pistache/blob/master/assets/images/logo.png) that you could upload somewhere? 
It would be more appropriate to use a vector image instead of a rastered one, even though PNGs work just fine.
