### ISSUE TITLE
[BUG] Listener stucked forever on blocking SSL read

### ISSUE THREAD

**Issue by kocica** [pistacheio/pistache#868]
On our production server there happened strange error, where all connections were closed and client could not create a new one.
Later on we found out our listener thread stucked in blocking SSL reading and could not serve anymore:

![attachments](https://user-images.githubusercontent.com/22328693/108387586-0261bb00-720e-11eb-8a13-ace627e02968.png)

[Here](http://openssl.6102.n7.nabble.com/SSL3-accept-makes-Server-stuck-td19511.html) I found out we can set SO_KEEPALIVE to our listener socket to detect that client is down and abort the blocking reading. I added the keepalive option [here](https://github.com/pistacheio/pistache/blob/0d09ab982edd03bc8457fa6351af7d0c4a135da2/src/server/listener.cc#L123).

May I ask why there is not such an option yet? Shouldn't it be added? Thank you

**Comment by kiplingw** [comment]
Thanks @kocica. Please use the bug reporting template to ensure we have all the information we need. Thanks a lot.

**Comment by vyivanov** [comment]
@kocica I faced with the same issue and deployed fixed app with suggested option in pistache for testing. Did you provide PR? I could prepare it...

**Comment by kocica** [comment]
Unfortunately I do not have time to create a PR, but here is what I did in order to get rid of that error:

1) Added KeepAlive option in `tcp.h`:

```
enum class Options : uint64_t {
    None                 = 0,
    NoDelay              = 1,
    Linger               = NoDelay << 1,
    FastOpen             = Linger << 1,
    QuickAck             = FastOpen << 1,
    ReuseAddr            = QuickAck << 1,
    ReusePort            = ReuseAddr << 1,
    KeepAlive            = ReusePort << 1
};
```

2) Handling of KeepAlive option in `listener.cc`:

```
if (options.hasFlag(Options::KeepAlive)) {
  int one = 1;
  TRY(::setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &one, sizeof (one)));
}
```

3) Set KeepAlive flag in your source codes when creating endpoint:

```flags.setFlag(Tcp::Options::KeepAlive);```


</body>
</html>

**Comment by vyivanov** [comment]
Yes, i also had got solution like that. Seems test is ok so far. Okay, i'll try to incorporate PR to upstream...

**Comment by vyivanov** [comment]
Eventually the problem reproduced after 2 days with such approach...
```
root@84bc901ab388:/var/www# curl -v https://application:9443   
*   Trying 172.19.0.4:9443...
* TCP_NODELAY set
* Connected to application (172.19.0.4) port 9443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):

. . . stuck . . .
```
