### ISSUE TITLE
Lots of issues need to be closed

### ISSUE THREAD

**Issue by Tachi107** [pistacheio/pistache#874]
After browsing the GitHub issue tracker, I noticed that a lot of old issues are now fixed, invalid, duplicated, or stale. 
I've written down almost all of them, but I've probably missed some.

- #27
- #31
- #40
- #70
- #73
- #80
- #86
- #88
- #92
- #94
- #100
- #105
- #106
- #109
- #120 (?)
- #126
- #135
- #148 (?)
- #150
- #164
- #176 (documentation related)
- #181
- #182 (duplicate of #239)
- #183
- #193
- #210 (duplicate of #399)
- #213 (to test on a Raspberry)
- #218
- #219 (not relevant?)
- #234 (mostly fixed by the documentation rewrite, could this be used to track all documentation-related issues?)
- #240 (not related to pistache)
- #242
- #243 (user either solved the issue itself or used another framework)
- #251 (all tests in CI pass, no response from author)
- #261 (not relevant)
- #267 (duplicate of #399)
- #278
- #282
- #292
- #317 (not an issue)
- #352 (all tests in CI pass, should retry with latest master)
- #357
- #364 (probably fixed by mentioned PR)
- #381
- #466 (no response)
- #505
- #513 (no response, probably fixed since headers are now case-insensitive)
- #526
- #530 (no response)
- #553 (no response)
- #562
- #567
- #572
- #587 (no response)
- #601
- #603 (relevant to docs, #234)
- #612
- #618
- #631
- #634
- #635 (no response)
- #643 (not relevant)
- #646 (not relevant)
- #647 (fixed)
- #664
- #667 (not an issue)
- #708 (seems fixed)
- #730
- #737 (not related to Pistache)
- #741 (Windows is not supported)
- #742
- #744 (documentation related)
- #747 (related to #493)
- #748
- #757
- #760 (no OSX support)
- #769
- #771
- #773
- #787 (no response)
- #790
- #793 (documentation related)
- #822 (fixed by the Meson PR)
- #824

**Comment by kiplingw** [comment]
Thanks @Tachi107. Gone through the list and closed the majority of them.
