### ISSUE TITLE
[BUG] Can't install via cmake

### ISSUE THREAD

**Issue by itssme** [pistacheio/pistache#877]
## Current Behavior
I am trying to install pistache and use it within my project. This already worked about three months ago and I successfully installed pistache on one of my pcs. However this does not work anymore:

```cmake
sudo apt-get install libssl-dev
mkdir third_party
cd third_party || exit
git clone https://github.com/oktal/pistache.git
cd pistache
git submodule update --init
mkdir build
mkdir prefix
cd build
cmake -G "Unix Makefiles" \
      -DCMAKE_BUILD_TYPE=Release \
      -DPISTACHE_BUILD_EXAMPLES=true \
      -DPISTACHE_BUILD_TESTS=false \
      -DPISTACHE_BUILD_DOCS=false \
      -DPISTACHE_USE_SSL=true \
      -DPISTACHE_INSTALL=true \
      -DCMAKE_INSTALL_PREFIX=$PWD/../prefix \
      ../
make -j 4
sudo make install
````

First problem:

The install fails because no install target exists in the makefile.

```bash
[ 91%] Built target pistache
Scanning dependencies of target pistache_static
Scanning dependencies of target pistache_shared
[ 95%] Linking CXX static library libpistache.a
[100%] Linking CXX shared library libpistache-0.0.002-git20210107.so
[100%] Built target pistache_static
[100%] Built target pistache_shared
make: *** No rule to make target 'install'.  Stop.
```

Second problem:

Even for the old build that worked I had to set the pistache_dir manually for cmake because it could not be detected by cmake otherwise. I tried the package install via the ppa but I have the same problem.

```cmake
set(Pistache_DIR "${CMAKE_SOURCE_DIR}/third_party/pistache/prefix/lib/cmake/pistache") 
find_package(Pistache REQUIRED)
target_link_libraries(rawStream ${OpenCV_LIBS} pistache_shared ${LIBS})
````

While the new build with meson works it does not generate the /pistache/prefix/lib/cmake/pistache folder for cmake anymore?? So I can't use it in my project..

## Expected behavior
This should install the pistache library.

## Context (Environment)

- Pistache version: newest git clone
- Operating System: Ubuntu 20.04 and Debian 10 (both with the same problem)
- Architecture: amd64
- Installed from: Built from source
- Used `pkg-config`: no

**Comment by kiplingw** [comment]
Thanks for reporting @itssme. The build environment now uses Meson. 

But unless you actually need to modify the source, that shouldn't matter. Please don't include a local copy in your source tree. It just creates a maintenance burden for you. Use instead the pre-compiled packages in the unstable PPA and link via `pkg-config` as detailed in the readme.

**Comment by itssme** [comment]
Ok thank you for the fast response. I installed the package and now link like: `target_link_libraries(rawStream ${OpenCV_LIBS} pistache ${LIBS})`

Everything works despite `find_package(Pistache REQUIRED)` failing, but I will just ignore this for now.

**Comment by kiplingw** [comment]
Check out [this](https://github.com/pistacheio/pistache/#cmake) section in the readme. What do you see when you run the following?

```sh
pkg-config --cflags --libs libpistache
```

**Comment by itssme** [comment]
It correctly finds pistache:
```bash
$ pkg-config --cflags --libs libpistache
-I/usr/include/ -L/usr/lib/x86_64-linux-gnu/ -lpistache -pthread -lssl -lcrypto
```

My cmake version is:
```bash
$ cmake --version
cmake version 3.16.3
```

And I am running a completely fresh install of ubuntu 20.04 with kernel 5.10

**Comment by kiplingw** [comment]
You removed the following line, correct?
```
set(Pistache_DIR "${CMAKE_SOURCE_DIR}/third_party/pistache/prefix/lib/cmake/pistache") 
```

Can you show us the complete CMake file and log?

**Comment by itssme** [comment]
Yes I removed that line.

I just tried the example and it gives me an error:
```bash
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  cmake_minimum_required called with unknown argument "3.4".


CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "FindPistache.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pistache",
  but CMake did not find one.

  Could not find a package configuration file provided by "Pistache"
  (requested version 0.0.2) with any of the following names:

    PistacheConfig.cmake
    pistache-config.cmake

  Add the installation prefix of "Pistache" to CMAKE_PREFIX_PATH or set
  "Pistache_DIR" to a directory containing one of the above files.  If
  "Pistache" provides a separate development package or SDK, be sure it has
  been installed.
```

I think the cmake version requirement is maybe wrong?
The function should look something like this:
```bash
cmake_minimum_required(VERSION 3.4 FATAL_ERROR)
```

Looking at the documentation the VERSION entry is mandatory: https://cmake.org/cmake/help/v3.4/command/cmake_minimum_required.html

----

However the example then fails because the package cannot be found.
Here is the complete error log:
https://pastebin.com/6tT4whhS

**Comment by itssme** [comment]
When I configure the cmake file of the example like:
```bash
cmake_minimum_required(VERSION 3.4 FATAL_ERROR)
project("MyPistacheProject")

# Find the library.
#find_package(Pistache 0.0.2 REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} pistache)
```

It works fine and I could see the "Hello World" in my browser.

**Comment by kiplingw** [comment]
It looks like our instructions are wrong for using `pkg-config` with CMake in the readme. @Tachi107 was the last to modify that section of the readme, but I think he simply moved it around rather than modifying it. The instructions we have I don't think actually use `pkg-config`, despite being under the section for its usage, which is likely your problem. That explains why it still builds because the library and headers are still correctly installed by the system package manager, even though the build environment isn't finding the `pkg-config` manifest.

[This](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) is how you use `pkg-config` correctly with CMake.

@Tachi107, would you kindly correct the readme when you get a chance?

**Comment by itssme** [comment]
Thank you! The new example helped me a lot :+1:

**Comment by kiplingw** [comment]
Thank @Tachi107!
