### ISSUE TITLE
[BUG] meson: error: unrecognized arguments: -C build

### ISSUE THREAD

**Issue by hyperxor** [pistacheio/pistache#880]
## Current Behavior
I'm following the manual on project main page to build `Pistache`:
```
$ cd pistache
$ meson setup build \
    --buildtype=release \
    -DPISTACHE_USE_SSL=true \
    -DPISTACHE_BUILD_EXAMPLES=true \
    -DPISTACHE_BUILD_TESTS=true \
    -DPISTACHE_BUILD_DOCS=false \
    --prefix=$PWD/prefix
$ meson compile -C build
$ meson install -C build
```
and get the following error:
```
$ meson compile -C build
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite} ...
meson: error: unrecognized arguments: -C build
```

## Expected behavior
Successful build from source.

## Steps to reproduce the bug
Fetch last sources, go to pistache source directory, execute:
```
$ meson setup build --buildtype=release -DPISTACHE_USE_SSL=true -DPISTACHE_BUILD_EXAMPLES=true     -DPISTACHE_BUILD_TESTS=true -DPISTACHE_BUILD_DOCS=false --prefix=$PWD/prefix
```

## Context (Environment)

- Operating System: Ubuntu 20.04.1
- Architecture: x86_64
- Installed from: Built from source

**Comment by Tachi107** [comment]
The `meson compile` command was added in Meson 0.54, but Ubuntu 20.04 ships version  0.53. 
What `meson compile` does is calling the backend that actually runs build commands (`ninja`, `msbuild`...), just like `cmake --build` does, so you can simply run `ninja -C build`

**Comment by hyperxor** [comment]
@Tachi107 thank you so much
