### ISSUE TITLE
[BUG] main': /home/pathawee/cpp_api/api.cpp:16: undefined reference to

### ISSUE THREAD

**Issue by pathawee1993** [pistacheio/pistache#884]
Hello everyone,
I'm newbie in build, make and i try to use Pistache in debian, i just build the code using meson. and all header are now stored in /user/include/pistache. i try to compiled using vscode and i got this error :D. Could someone tell me how to slove this. 
**compiler
g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
**

** error code
Starting build...
/usr/bin/g++ -g /home/pathawee/cpp_api/api.cpp -o /home/pathawee/cpp_api/api
/usr/bin/ld: /tmp/ccgBURqQ.o: in function `main':
/home/pathawee/cpp_api/api.cpp:16: undefined reference to `Pistache::Port::Port(unsigned short)'
/usr/bin/ld: /home/pathawee/cpp_api/api.cpp:16: undefined reference to `Pistache::IP::any()'
/usr/bin/ld: /home/pathawee/cpp_api/api.cpp:16: undefined reference to `Pistache::Address::Address(Pistache::IP, Pistache::Port)'
/usr/bin/ld: /home/pathawee/cpp_api/api.cpp:18: undefined reference to `Pistache::Http::Endpoint::options()'
/usr/bin/ld: /home/pathawee/cpp_api/api.cpp:18: undefined reference to `Pistache::Http::Endpoint::Options::threads(int)'
/usr/bin/ld: /home/pathawee/cpp_api/api.cpp:19: undefined reference to `Pistache::Http::Endpoint::Endpoint(Pistache::Address const&)'
/usr/bin/ld: /home/pathawee/cpp_api/api.cpp:20: undefined reference to `Pistache::Http::Endpoint::init(Pistache::Http::Endpoint::Options const&)'
/usr/bin/ld: /home/pathawee/cpp_api/api.cpp:21: undefined reference to `Pistache::Http::Endpoint::setHandler(std::shared_ptr<Pistache::Http::Handler> const&)'
/usr/bin/ld: /home/pathawee/cpp_api/api.cpp:22: undefined reference to `Pistache::Http::Endpoint::serve()'
/usr/bin/ld: /tmp/ccgBURqQ.o: in function `Pistache::Http::Handler::~Handler()':
/usr/local/include/pistache/http.h:587: undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: /usr/local/include/pistache/http.h:587: undefined reference to `Pistache::Tcp::Handler::~Handler()'
/usr/bin/ld: /tmp/ccgBURqQ.o: in function `Pistache::Http::Endpoint::~Endpoint()':
/usr/local/include/pistache/endpoint.h:16: undefined reference to `Pistache::Tcp::Listener::~Listener()'
/usr/bin/ld: /tmp/ccgBURqQ.o: in function `Pistache::Async::Promise<long> Pistache::Http::ResponseWriter::send<14ul>(Pistache::Http::Code, char const (&) [14ul], Pistache::Http::Mime::MediaType const&)':
/usr/local/include/pistache/http.h:382: undefined reference to `Pistache::Http::ResponseWriter::sendImpl(Pistache::Http::Code, char const*, unsigned long, Pistache::Http::Mime::MediaType const&)'
/usr/bin/ld: /tmp/ccgBURqQ.o: in function `Pistache::Tcp::Handler::Handler(Pistache::Tcp::Handler const&)':
/usr/local/include/pistache/tcp.h:35: undefined reference to `vtable for Pistache::Tcp::Handler'
/usr/bin/ld: /tmp/ccgBURqQ.o: in function `Pistache::Http::Handler::Handler(Pistache::Http::Handler const&)':
/usr/local/include/pistache/http.h:576: undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: /tmp/ccgBURqQ.o: in function `Pistache::Http::Handler::Handler()':
/usr/local/include/pistache/http.h:576: undefined reference to `Pistache::Tcp::Handler::Handler()'
/usr/bin/ld: /usr/local/include/pistache/http.h:576: undefined reference to `vtable for Pistache::Http::Handler'
/usr/bin/ld: /tmp/ccgBURqQ.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x28): undefined reference to `Pistache::Http::Handler::onInput(char const*, unsigned long, std::shared_ptr<Pistache::Tcp::Peer> const&)'
/usr/bin/ld: /tmp/ccgBURqQ.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x30): undefined reference to `Pistache::Http::Handler::onConnection(std::shared_ptr<Pistache::Tcp::Peer> const&)'
/usr/bin/ld: /tmp/ccgBURqQ.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x38): undefined reference to `Pistache::Tcp::Handler::onDisconnection(std::shared_ptr<Pistache::Tcp::Peer> const&)'
/usr/bin/ld: /tmp/ccgBURqQ.o:(.data.rel.ro._ZTV12HelloHandler[_ZTV12HelloHandler]+0x48): undefined reference to `Pistache::Http::Handler::onTimeout(Pistache::Http::Request const&, Pistache::Http::ResponseWriter)'
/usr/bin/ld: /tmp/ccgBURqQ.o:(.data.rel.ro._ZTI12HelloHandler[_ZTI12HelloHandler]+0x10): undefined reference to `typeinfo for Pistache::Http::Handler'
collect2: error: ld returned 1 exit status

**Comment by Tachi107** [comment]
It seems that the linker can't find the Pistache library. 
If you've correctly installed Pistache you can tell your compiler to link the program with the library by passing `-lpistache` to `g++`. 

I would recommend using a build system though, so that you don't have to manually track all the build flags that you need. I would suggest you to use Meson, as it is quite simple. If so, you can add Pistache as a dependency for your program following the [instructions in the Readme](https://github.com/pistacheio/pistache#meson).

**Comment by Tachi107** [comment]
@pathawee1993 I'm closing this since this isn't a Pistache issue. If you need help, feel free to reply to this thread
