### ISSUE TITLE
[PROBLEM] pthread_create problem on cmake build

### ISSUE THREAD

**Issue by nilsvennemann** [pistacheio/pistache#885]
![image](https://user-images.githubusercontent.com/58829732/113854626-5cf3ae00-979f-11eb-8b9c-75c21579eb3b.png)

I have this error pthread_create undefined reference why?

**Comment by nilsvennemann** [comment]
I fix it with: 

`
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
target_link_libraries(ProjectName PRIVATE Threads::Threads)
`

**Comment by kiplingw** [comment]
Thanks for reporting, @nilsvennemann. But please use the bug report template.
