### ISSUE TITLE
no template named 'optional' in namespace 'std'

### ISSUE THREAD

**Issue by Cumbiambero** [pistacheio/pistache#905]
after upgrading the library from the Ubuntu repository (version 0.0.002-git20210409) I get the following error:

```
usr/include/pistache/mime.h:199:28: error: no template named 'optional' in namespace 'std'
                const std::optional<Q>& q() const { return q_; }
                      ~~~~~^
```

**Comment by Tachi107** [comment]
Pistache is in the progress of upgrading to C++17. What compiler and C++ version are you using?

**Comment by kiplingw** [comment]
@Cumbiambero, try adding `-std=c++17` to your list of compiler switches.

**Comment by Cumbiambero** [comment]
Thank you very much. 
Setting the following in CMakeLists.txt
`set(CMAKE_CXX_STANDARD 17)`
and changing `find_package(Pistache 0.0.2 REQUIRED)` to`find_package(PkgConfig)
pkg_check_modules(Pistache REQUIRED IMPORTED_TARGET libpistache)`, chaning `target_link_libraries(${PROJECT_NAME} pistache_shared)` to `target_link_libraries(${PROJECT_NAME} PkgConfig::Pistache)` solved the mentioned problem.

Then I had to replace in my code all teh methods calls form `Optional` by methods from `std::optional` like `getOrElse()` by `value_or()` for example.
