### ISSUE TITLE
[FEATURE REQUEST] (cmake install)

### ISSUE THREAD

**Issue by EMHussain** [pistacheio/pistache#908]
## Install pistache via cmake.
Please add cmake install support i am successfully able to build with cmake but unable to install.

**Comment by Tachi107** [comment]
Pistache has switched to the Meson build system a while ago; you can find instructions on how to install it from source on pistache.io.

Why do you need to be able to install the library using CMake?

**Comment by EMHussain** [comment]
It want to build for android, I am not much familiar with meson build for android.

**Comment by Tachi107** [comment]
What are you trying to achieve exactly? This isn't really a Pistache issue, since Meson supports cross-compiling, but (re)adding the install target wouldn't be difficult either.

**Comment by EMHussain** [comment]
Ok alright I can re add install targets thanks.
