### ISSUE TITLE
[BUG] Request timeout 408

### ISSUE THREAD

**Issue by Cumbiambero** [pistacheio/pistache#915]
## Current Behavior
When running a JMeter test I get a high percentage of request timeouts (408). I added the sources of the implementation to the issue.
[completeSources.zip](https://github.com/pistacheio/pistache/files/6419360/completeSources.zip)

I didn't have those timeouts before upgrading pistache. I have attached the Test (PerformanceTests.jmx) and the result (other frameworks are tested as well) in this file:
[test.zip](https://github.com/pistacheio/pistache/files/6419339/test.zip)

## Expected behavior
All the requests should return with 200 OK.

## Possible Solution
Maybe I am doing something wrong in my implementation or maybe there is really an issue.

## Steps to reproduce the bug
Build and start the application. It will listen on port 8084 and serve 2 endpoints 

- / for a HelloWorld!
- /primes?limit=10000 (the limit until primes shall be searched). The count and a list of integers are returned as JSON.

All the content is included in the zip file. Then run the JMeter test:
`jmeter -el log.log -nt PerformanceTests.jmx -o results`

## Context (Environment)

- Pistache version: 0.0.002-git20210409
- Operating System: Linux virtualbox 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Architecture: amd64
- Installed from: unstable
- Used `pkg-config`: no

**Comment by hyperxor** [comment]
@Cumbiambero Hello, this bug will be fixed in this PR #912 
cc @kiplingw

**Comment by Cumbiambero** [comment]
@hyperxor Thank you very much for the information and your contribution. I checked out your branch and repeated the tests. Unfortunately I still get the errors:
[fix_issue_842_and_refactoring.zip](https://github.com/pistacheio/pistache/files/6425355/fix_issue_842_and_refactoring.zip)

Here you can see that at march 25 the problem didn't occur:
[beforeUpdate.zip](https://github.com/pistacheio/pistache/files/6425350/beforeUpdate.zip)

**Comment by Tachi107** [comment]
@Cumbiambero what version (or commit hash) of the library were you using before the update?

**Comment by Cumbiambero** [comment]
@Tachi107 It's difficult to say. I locally retrieved the library from the Ubuntu Repository (ppa:pistache+team/unstable) or build it directly from sources for the Docker image. Maybe it is related to https://github.com/pistacheio/pistache/issues/905 where I experienced some changes regarding the upgrade to C++17?

**Comment by hyperxor** [comment]
@Cumbiambero I have reproduced your problem. Something is wrong with `headerTimeout_` and `bodyTimeout_` values in `TransportImpl` class: `140075036416944` and `94186459123680`. I will investigate this problem.

**Comment by hyperxor** [comment]
@Cumbiambero Hello, I have found yet another problem in Pistache code. [This](https://github.com/pistacheio/pistache/pull/912/commits/4e33c220f48b6be298808529972eacb6139e254a) is fix.
I have tried your jmeter perfomance test and everything is ok now _in my environment_:
```
...
Waiting for possible shutdown message on port 4445
summary +  12832 in    10s = 1339.3/s Avg:   129 Min:     0 Max:  1999 Err:     0 (0.00%) Active: 1000 Started: 1000 Finished: 0
summary +  87168 in  28.1s = 3103.9/s Avg:    19 Min:     0 Max:   853 Err:     0 (0.00%) Active: 0 Started: 1000 Finished: 1000
summary = 100000 in    38s = 2655.0/s Avg:    33 Min:     0 Max:  1999 Err:     0 (0.00%)
...
```
Can you pull the latest update from my branch `fix_issue_842_and_refactoring` and check it?

**Comment by Cumbiambero** [comment]
@hyperxor Thank you. Maybe it is something environment specific. I still have the problem.  I added logging and observed that after some requests the Docker container dies and I get connection refused. I will now switch from the repository version to your version also on my local machine and then investigate with valgrind.

**Comment by Cumbiambero** [comment]
@hyperxor Seems like the errors I got came from the added logging.

**Comment by Cumbiambero** [comment]
@hyperxor I can confirm that your fix solved the problem completely. Excellent work!

**Comment by hyperxor** [comment]
@Cumbiambero you are welcome!
