### ISSUE TITLE
thirdparty is not installed properly

### ISSUE THREAD

**Issue by jviki** [pistacheio/pistache#950]
The `thirdparty/` include files are not installed at all.

Reproduce:

```shell
meson . build/
ninja -j9 -C build/
DESTDIR=`pwd`/_install ninja -C build/ install
```

Output from install step:

```
ninja: Entering directory `build/'
[0/1] Installing files.
Installing subdir include/pistache/thirdparty to _install/usr/local/include/pistache/thirdparty
Installing src/libpistache.so.0.0.002 to _install/usr/local/lib
Installing include/pistache/async.h to _install/usr/local/include/pistache
Installing include/pistache/base64.h to _install/usr/local/include/pistache
Installing include/pistache/client.h to _install/usr/local/include/pistache
...
Installing include/pistache/view.h to _install/usr/local/include/pistache
Installing include/pistache/version.h to _install/usr/local/include/pistache
Installing meson-private/libpistache.pc to _install/usr/local/lib/pkgconfig
```

Directory `_install/usr/local/include/pistache/thirdparty` is empty but should contain at least `serializer/rapidjson.h`.

Builds of my application fails with:

```
fatal error: pistache/thirdparty/serializer/rapidjson.h: No such file or directory
   18 | #include <pistache/thirdparty/serializer/rapidjson.h>
```

**Comment by Tachi107** [comment]
I'm not sure, but this is probably related to #936. Since `serializer/rapidjson.h` wasn't actually a third party header it has been moved to its original location, `pistache/serializer/rapidjson.h`

**Comment by Tachi107** [comment]
Oh ok, I think that the problem here is the fact that in [`include/pistache/meson.build`](https://github.com/pistacheio/pistache/blob/master/include/pistache/meson.build) the `serializer/rapidjson.h` file is not part of `install_headers()`. I always forget about something

**Comment by kiplingw** [comment]
Good eye @Tachi107.

**Comment by Tachi107** [comment]
@jviki, could you check if #951 fixes your issue?

**Comment by jviki** [comment]
Well, it works better now. I am curious, why you break the compatibility by changing the path? I now have to put some `#ifdefs` into my code because originally (or whatever) it was located in `pistache/thirdparty`. Hopefully, you provide some usable version `#define` to make this properly.

**Comment by jviki** [comment]
> Hopefully, you provide some usable version #define to make this properly.

I only found `version.h.in` that provides non-preprocessorable version info data. I build the library on about 3 different platforms, how can I make sure that all of them successfully include the "thirdparty" header?

**Comment by Tachi107** [comment]
> why you break the compatibility by changing the path?

Pistache hasn't yet hit a 1.0 release (but we should be close). That means that while keeping backwards compatibility is nice it is not guaranteed. Since we are approaching the first release I'm trying to make all the breaking changes before this "freedom" of breaking stuff finishes. As for why this specific change, it was confusing to have a first party header in a `thirdparty` directory.

> I only found version.h.in that provides non-preprocessorable version info data.

You're right, at the moment we don't provide any version #defines... I think that for the time being the only thing you can do is to manually check that you are using the same git commit :/
