### ISSUE TITLE
Documentation doesn't say this is incompatible with Mac OS

### ISSUE THREAD

**Issue by Stokestack** [pistacheio/pistache#960]
Nowhere do I see a notice that this project won't build on a Mac (compilation fails with "error: unknown type name 'cpu_set_t'", [a reported problem](https://github.com/pistacheio/pistache/issues/760)).

Please add this notice prominently, so developers don't waste time attempting to build this product.

Thanks!

**Comment by Tachi107** [comment]
I agree, in fact this has already been pointed out in https://github.com/pistacheio/pistache/issues/825#issuecomment-871320363.

Will do as soon as I'll get back home :)

**Comment by Stokestack** [comment]
I appreciate that!
