### ISSUE TITLE
Does latest precompiled packages provide SSL feature?

### ISSUE THREAD

**Issue by KangJH** [pistacheio/pistache#963]
First of all thank you for providing this nice library.
I have a quick question.

Does [stable](https://launchpad.net/~pistache+team/+archive/ubuntu/stable) version of pistach provide SSL feature?
I checked `PISTACHE_USE_SSL` in CMakeLists.txt is default off.
To use SSL feature, then should I build package manually?

Thanks,

**Comment by kiplingw** [comment]
At present there is no stable release in the PPA. We plan on releasing a stable release shortly. In the mean time, to the best of my knowledge the unstable binaries are built with SSL support.
