### ISSUE TITLE
Package for Ubuntu 20.04 has been removed ?!?

### ISSUE THREAD

**Issue by FredM67** [pistacheio/pistache#978]
Since 1-2 days, the package for Ubuntu 20.04 LTS doesn't exist anymore... is there any reason for that?

**Comment by Tachi107** [comment]
Hi, that's my fault. The PPA was having some issues updating packages for Ubuntu 20.04 (and no other distributions), and I was looking into how to solve the issue. I probably deleted it by mistake. 
I've now triggered a rebuild; a new package should be available in a few minutes. Sorry!

**Comment by FredM67** [comment]
Hey, cool.... thx A LOT .....

**Comment by FredM67** [comment]
Hm... still does not work... do you know how long it takes until the package can be downloaded through apt-get ?

**Comment by Tachi107** [comment]
@FredM67 you can see [here](https://launchpad.net/~pistache+team/+archive/ubuntu/unstable/+sourcepub/12707049/+listing-archive-extra) that the package has been built successfully and is now being published to the PPA. 
If you can't wait, you can directly download the .deb from there

**Comment by FredM67** [comment]
I can wait... that's just a question how long it takes !

**Comment by Tachi107** [comment]
I have no idea :/
Shouldn't take more than an hour, I guess.

**Comment by FredM67** [comment]
Ok, now I get another error, here's what apt-get says:
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpistache-dev : Depends: libpistache0 (= 0.0.002+git20210913.918a95d~ubuntu20.04.1) but 0.0.002+git202109032203.5572710~ubuntu20.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Tachi107** [comment]
Yes, that's because `apt` is having the same issue as the PPA had... 
You can run `sudo apt install --allow-downgrades libpistache-dev=0.0.002+git20210913.918a95d~ubuntu20.04.1 libpistache0=0.0.002+git20210913.918a95d~ubuntu20.04.1` to "downgrade" the package, even if this actually is an upgrade.

This happened because apt thinks that `20210913` is smaller than `202109032203`, and so sees the new version as older than the one already installed.

This will be fixed automatically for everybody once the 1.0 release will be released

**Comment by FredM67** [comment]
Again thx a lot for efficient and quick support...

**Comment by Tachi107** [comment]
@kiplingw could you pin this? This requires manual intervention from Ubuntu 20.04 users until 1.0 is released

**Comment by FredM67** [comment]
> @kiplingw could you pin this? This requires manual intervention from Ubuntu 20.04 users until 1.0 is released

I think, that's only for those who already installed an older version before. For installation from scratch (without history), no extra action is needed.
