### ISSUE TITLE
Build errors using meson

### ISSUE THREAD

**Issue by nbommersbach** [pistacheio/pistache#985]
Hello,
I had problems building pistache from source as meson could not find openssl. I solved this by tweaking around with the openssl visibility settings and finally could make it visible to pkg-config. I was then able to successfully generate the build folder using:

`meson setup build \
    --buildtype=release \
    -DPISTACHE_USE_SSL=true \
    -DPISTACHE_BUILD_EXAMPLES=true \
    -DPISTACHE_BUILD_TESTS=true \
    -DPISTACHE_BUILD_DOCS=false \
    --prefix=$PWD/prefix`

Running the next step from that README (`meson compile -C build`) left me with countless errors I cannot identify and solve:

`ninja: Entering directory `build'
[1/138] Compiling C++ object src/libpistache.0.0.dylib.p/common_stream.cc.o
FAILED: src/libpistache.0.0.dylib.p/common_stream.cc.o 
c++ -Isrc/libpistache.0.0.dylib.p -Isrc -I../src -Iinclude -I../include -I../subprojects/rapidjson-1.1.0/include -I../subprojects/hinnant-date/include -I/usr/local/Cellar/openssl@1.1/1.1.1l/include -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Wconversion -Wno-sign-conversion -Wno-missing-field-initializers -DPISTACHE_USE_SSL -MD -MQ src/libpistache.0.0.dylib.p/common_stream.cc.o -MF src/libpistache.0.0.dylib.p/common_stream.cc.o.d -o src/libpistache.0.0.dylib.p/common_stream.cc.o -c ../src/common/stream.cc
In file included from ../src/common/stream.cc:12:
In file included from ../include/pistache/stream.h:15:
../include/pistache/os.h:55:9: error: unknown type name 'cpu_set_t'
        cpu_set_t toPosix() const;
        ^
1 error generated.
[2/138] Compiling C++ object src/libpistache.0.0.dylib.p/common_net.cc.o
FAILED: src/libpistache.0.0.dylib.p/common_net.cc.o 
c++ -Isrc/libpistache.0.0.dylib.p -Isrc -I../src -Iinclude -I../include -I../subprojects/rapidjson-1.1.0/include -I../subprojects/hinnant-date/include -I/usr/local/Cellar/openssl@1.1/1.1.1l/include -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Wconversion -Wno-sign-conversion -Wno-missing-field-initializers -DPISTACHE_USE_SSL -MD -MQ src/libpistache.0.0.dylib.p/common_net.cc.o -MF src/libpistache.0.0.dylib.p/common_net.cc.o.d -o src/libpistache.0.0.dylib.p/common_net.cc.o -c ../src/common/net.cc
../src/common/net.cc:106:65: error: no member named 's6_addr16' in 'in6_addr'
            int res = inet_pton(AF_INET6, host.c_str(), &(addr6.s6_addr16));
                                                          ~~~~~ ^
../src/common/net.cc:120:55: error: no member named 's6_addr16' in 'in6_addr'
                static_assert(sizeof(s_addr.sin6_addr.s6_addr16) >= 8 * sizeof(uint16_t),
                                     ~~~~~~~~~~~~~~~~ ^
../src/common/net.cc:122:43: error: no member named 's6_addr16' in 'in6_addr'
                memcpy(&(s_addr.sin6_addr.s6_addr16), &addr6.s6_addr16,
                         ~~~~~~~~~~~~~~~~ ^
../src/common/net.cc:122:62: error: no member named 's6_addr16' in 'in6_addr'
                memcpy(&(s_addr.sin6_addr.s6_addr16), &addr6.s6_addr16,
                                                       ~~~~~ ^
../src/common/net.cc:194:33: error: no member named 's6_addr16' in 'in6_addr'
        memcpy(&addr6.sin6_addr.s6_addr16, &remap, 8 * sizeof(uint16_t));
                ~~~~~~~~~~~~~~~ ^
../src/common/net.cc:212:38: error: no member named 's6_addr16' in 'in6_addr'
            memcpy(&(addr6.sin6_addr.s6_addr16), &(in_addr->sin6_addr.s6_addr16),
                     ~~~~~~~~~~~~~~~ ^
../src/common/net.cc:212:71: error: no member named 's6_addr16' in 'in6_addr'
            memcpy(&(addr6.sin6_addr.s6_addr16), &(in_addr->sin6_addr.s6_addr16),
                                                   ~~~~~~~~~~~~~~~~~~ ^
../src/common/net.cc:274:22: error: no member named 's6_addr16' in 'in6_addr'
        memcpy(&out->s6_addr16, &(addr6.sin6_addr.s6_addr16), 8 * sizeof(uint16_t));
                ~~~  ^
../src/common/net.cc:274:51: error: no member named 's6_addr16' in 'in6_addr'
        memcpy(&out->s6_addr16, &(addr6.sin6_addr.s6_addr16), 8 * sizeof(uint16_t));
                                  ~~~~~~~~~~~~~~~ ^
9 errors generated.
[4/138] Compiling C++ object src/libpistache.0.0.dylib.p/common_os.cc.o
FAILED: src/libpistache.0.0.dylib.p/common_os.cc.o 
c++ -Isrc/libpistache.0.0.dylib.p -Isrc -I../src -Iinclude -I../include -I../subprojects/rapidjson-1.1.0/include -I../subprojects/hinnant-date/include -I/usr/local/Cellar/openssl@1.1/1.1.1l/include -fcolor-diagnostics -DNDEBUG -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Wconversion -Wno-sign-conversion -Wno-missing-field-initializers -DPISTACHE_USE_SSL -MD -MQ src/libpistache.0.0.dylib.p/common_os.cc.o -MF src/libpistache.0.0.dylib.p/common_os.cc.o.d -o src/libpistache.0.0.dylib.p/common_os.cc.o -c ../src/common/os.cc
In file included from ../src/common/os.cc:14:
../include/pistache/os.h:55:9: error: unknown type name 'cpu_set_t'
        cpu_set_t toPosix() const;
        ^`

This goes on for quite a while. Does someone know what I can do? I am out of ideas.

**Comment by Tachi107** [comment]
What platform are you using?

**Comment by nbommersbach** [comment]
Sorry. I'm running macOS BigSur 11.5.2. standard compiler is Clang 12.0.0 apple darwin

**Comment by Tachi107** [comment]
Pistache currently uses Linux-specific APIs to do networking, so it can't be complied on macOS.

This is stated on the pistache.io website, but not in the Readme. I'll update it since a lot of people never visited the site. Sorry for the inconvenience!

**Comment by nbommersbach** [comment]
No problem and thanks for the answer!
